### ISSUE TITLE
Citation style: American Physics Society with title and doi

### ISSUE THREAD

**Issue by floaltvater** [dsifford/academic-bloggers-toolkit#107]
Would it be possible to implement the American Physics Society with title and doi link? Preferably like

J. D. Watson and F. H. C. Crick, "Molecular structure of nucleic acids; a structure for deoxyribose nucleic acid," Nature **171**, 737 (1953). doi:[10.1038/171737a0](https://doi.org/10.1038/171737a0)

Thanks!

**Comment by dsifford** [comment]
How does American Physics Society currently format that citation?

Have you checked [here](http://editor.citationstyles.org/searchByExample/) to see if there are other citations that match what you're looking for better?

**Comment by floaltvater** [comment]
This is what the above reference looks like in standard APS:

J. D. Watson and F. H. C. Crick, Nature **171**, 737 (1953).

And I already checked that page. Although Frontiers in Optics includes the title, it also puts the publisher in with the year, which I really don't like. That doesn't show on CSL, however, as it doesn't have publisher info in the examples. And it also is missing the doi.

I could probably fix it myself with a simple function that rearranges things, if implementing it is too complicated. I just figured I'd ask.

Or how hard would it be to implement it myself? If you point me in the right direction, I could have a go at it.

[https://journals.aps.org/authors/references-physical-review-physical-review-letters](https://journals.aps.org/authors/references-physical-review-physical-review-letters)
[http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Famerican-physics-society](http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Famerican-physics-society)

**Comment by dsifford** [comment]
@floaltvater 

Adding the ability to use user-defined CSL styles has actually been on my radar.

Let me finish up these last few stray bugs and I'll work on getting that implemented. Not able to give a timeframe, but assuming I don't run into any difficulties, it shouldn't take longer than a week or two.

**Comment by floaltvater** [comment]
Well, that would simply be amazing and border-line mind-blowing :) Thank you so much for your time and effort.

**Comment by dsifford** [comment]
@floaltvater 

Update: Implementing this was a little bit easier than I thought it would be.

I just finished an early working implementation which adds the ability to use custom user-defined CSL.

I'd be interested in some feedback on it prior to releasing this live. Let me know if you'd be willing to critique.

Thanks

**Comment by floaltvater** [comment]
I'd love to. Just let me know how I can get the non-live version to work. Will I have to compile it? (Running Linux, so that might help.) If so, any instructions/pointers are welcome, also since the contributer's guide says that it would need to be updated.

**Comment by dsifford** [comment]
@floaltvater Sorry for the delay in getting back with you.

I was originally thinking of just sharing a few screenshots and such with you for your comment, but if you're feeling up to pulling the repo and checking it out yourself, by all means!

I'll work on getting the contributing guide updated here in a few.

In the meantime, here's the gist of the next update:

### Peer review boxes fully depreciated.
I wrote the code for those when I was quite experienced. The result of which has had me pulling my hair out over the last few updates because of how sloppy things were handled. They may come back later on, but still not sure; had to get rid of them for now to keep my sanity.

### Ability to use a single custom citation style at a time.
I debated making it possible to load and use several custom citation styles at any given time, but decided against it. I figured once a site has the citations the way they want them, they'll generally be sticking to them in that format anyway. Having the ability to have multiple just adds too much unnecessary chaos to the backend.

The process of loading the custom citations is what I really wanted input on. I'm not sure how well it will be received. I was going to add a custom file uploader to the options page, but I decided against it because it would have added a bunch of complexity (and also because I dislike working with PHP in general).

Instead, it goes something like this... (this assumes that you already generated the citation style and have it saved to your disk)

1. Upload the `.csl` file using the wordpress media uploader.
    ![image](https://cloud.githubusercontent.com/assets/5240018/17686766/406d4b4c-633d-11e6-8365-d7f7d16fb0dd.png)
2. Copy the direct URL for the `.csl` file and paste it in an input field on the admin screen.
    ![image](https://cloud.githubusercontent.com/assets/5240018/17686777/61c4b4e2-633d-11e6-9f90-8253134acc5a.png)
3. Check `Use custom citation style by default` (or don't, it'll still be available to choose).
4. Once saved, go to the post screen and it'll show up first in the citation style picker.
    ![image](https://cloud.githubusercontent.com/assets/5240018/17686830/c364480c-633d-11e6-8b53-4673877ead41.png)

(the header heights will be reduced)

Does that seem too difficult for most to grasp? Any suggestions there?

### Fixed buggy footnote-style citations
Self-explanatory.

### Added 44 more citation styles to the default list
Self-explanatory

Thanks for the feedback!

**Comment by floaltvater** [comment]
I think that's pretty straight-forward. Especially if you document it like this somewhere. And I agree that one custom citation style should be fine for most cases.

Looking great!

I'll just wait then until you pushed the update.
