### ISSUE TITLE
Scrolling in citation style drop down list in hamburger menu broken

### ISSUE THREAD

**Issue by floaltvater** [dsifford/academic-bloggers-toolkit#109]
Sorry for adding so many things to your list...

I click on the "hamburger menu" on a page or post, to choose an individual citation style for that page/post. When I click and drag the scroll bar, I can see and scroll down to "American Chemical Society Author Date". Scrolling further down only shows whitespace instead of style names. When I scroll with the wheel, or release the scroll bar and move my mouse into the drop-down list, the list starts to jump downwards until there's only whitespace again. The jumping starts around entries with "Ad..." and ends in the whitespace, i.e., I can scroll normally through the entries starting with "Ac..." and the whitespace, but not in between.

Entering a style name manually works as expected, and shows any style beyond the accessible range mentioned above. However, when the number of search results is large (for example, when entering "American") the scroll issue appears again, roughly after the same number of entries as above. So it seems that the issue has to do with the number of entries that can be displayed and scrolled through in the drop-down before the jumping and whitespace happens.

Hope that description was clear enough. Using Firefox 48.0 if that has anything to do with it. The drop-down in the plugin settings works as expected, showing all entries and allows scrolling.

**Comment by dsifford** [comment]
No apology necessary! I appreciate the feedback. As you might have guessed, it's tough for just me to catch all the little stray bugs. By all means, keep 'em coming!

I noticed the scroll issue as well just a bit ago. I'll see if I can get it sorted out. 

The reason why it works on the options page vs the posts screen is because on the posts screen I'm forced to use a virtualized representation of the citation names, which allows for the options to lazy-load as you scroll. Without that, opening and closing the hamburger menu would be laggy since it would have to reload all 1300 citations each time.

I might end up switching to just an autocomplete box (sans dropdown) since there's really not enough room for the dropdown there anyway. Any suggestions you might have are welcomed.

Thanks again 👍

**Comment by floaltvater** [comment]
Autocomplete would definitely work, but is not quite as user friendly, I think.

What about having an extra option in the general settings to specify individual citation styles that would then appear in the posts screen drop-down? A comma-separated list maybe? Then it wouldn't have to load all styles when opening the menu.

In my case I would want to allow a handful of authors to specify their own citation style on their profile page. However, they don't need access to all 1300. And I assume not many people would need that.
