### ISSUE TITLE
A Page that lists all references 

### ISSUE THREAD

**Issue by danieldekay** [dsifford/academic-bloggers-toolkit#126]
I am working on a blog that discusses publications.
Ideally there would be an easy way to create a summary page of all publications that have been referenced by your toolkit.

**Comment by dsifford** [comment]
Closing in favor of #123

**Comment by danieldekay** [comment]
Don't see it as a duplicate. Whereas #123 wants a publication list for one page or post, I want it for the whole site, incoporating all citations ever made.

**Comment by dsifford** [comment]
@danieldekay Not sure I understand the use-case.

Can you explain this a bit further?

**Comment by JLJu** [comment]
@dsifford I understand the needs expressed by @danieldekay 

We've got on our project site a web page with all the references used within all the articles, with the correct numbers(article dependent) and the hyperlinks to the correct articles pages. All the references were created by hand, so It's some work.

The first time I saw your plugin I tried to use it just as @danieldekay suggest.
Now we are using your plugin and we have dropped the centralized approach :-)

The point is that that the here required web page is not standard(at least I don't know where to find that standard) , it is not a plain bibliography but it is a bit more complex and with dynamic content.

Thank you for your work!

**Comment by dsifford** [comment]
@JLJu Do you have some example of this somewhere that I can take a look at? Still not sure I'm understanding completely.

**Comment by JLJu** [comment]
Sure thing @dsifford 
I have some old HTML fragment from the CMS.

Imagine this section placed within a file "Reference.html", the example shows the references of the Pitot page only.  Each page with references cited should have a manual section(with proper anchor) created within the "Reference.html". 

```
<a name="PitotPage"></a>   <- Anchor to section
<b class="imUl fs16">Pitot page references</b>
<a class="imCssLink" href="http://basicairdata.eu/pitot-test.html">Back to Pitot Test page</a> <- Link to the original page that contain citations
<ol>
<li><span class="fs13">Edward A.Haering, Jr (1995), Airdata Measurement and Calibration, Nasa
</span><span class="fs13"><a class="imCssLink" href="http://spaceagecontrol.com/nasa-tm-104316.pdf" target="_blank">Retrieved</a></span><span class="fs13"><span class="fs13"> 17/4/2013</span></span></li>
<li><span class="fs13">John V.Foster and Kevin Cunningham, </span><span class="fs13">GPS-Based Pitot-Static Calibration Method Using Global</span> <span class="fs13">Output-Error Optimization,</span> <span class="fs13">American Institute of Aeronautics and Astronautics
</span><span class="fs13"><a class="imCssLink" href="http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20100002809_2010002328.pdf" target="_blank">Retrieved</a></span><span class="fs13"> 19/5/2013</span></li>
<li><span class="fs13"><a class="imCssLink" href="http://en.wikipedia.org/wiki/Central_limit_theorem" target="_blank">Central Limit therorem</a></span><span class="fs13">;</span></li>
<li><span class="fs13">NIST (View 12-4-2013), Law of Propagation of Uncertainty, A-3, NIST
</span><span class="fs13"><a class="imCssLink" href="http://physics.nist.gov/Pubs/guidelines/appa.html" target="_blank">Retrieved</a></span><span class="fs13"> 17/4/2013
</span><span class="fs13"><a class="imCssLink" href="http://physics.nist.gov/Pubs/guidelines/TN1297/tn1297s.pdf" target="_blank">Downloadable complete Technical note</a></span>;</li>```

It is a simple ordered list of the references present within the Pitot page.  The numbers cited here are exactly the number used within the Pitot page text. Within the pitot page text, an hyperlink (for example starting from [1]) is pointing from each insertion point to the correct section within Reference.html.  In fact, within the article page the Reference details are not present (nothing, not a word). Note also that the hyperlink to the source page(in the example the pitot page) should be present within the Reference.html page dedicated section.

All these links, back and forth, were placed by hand That was a process prone to errors.

**Comment by dsifford** [comment]
@JLJu What is the benefit of having references detached from the referring document? IMHO, that pattern sounds like it will ostensibly make fact checking and portability of academic writings much more difficult to accomplish (the latter of which is not just difficult; but impossible).

With all due respect, and perhaps I could still be misinterpreting the utility and use-case of your example, I just don't agree with that pattern and it's not something I'd want to be promoting with this plugin.

If this is something that you simply _must_ have, you might be able to get away with it using another plugin (eg. Zotpress). Zotpress saves a maximal representation of all references that you import directly to your database, so this might even be easier to accomplish using that plugin.

The data saved by ABT is a fraction of the size of the data saved by plugins like Zotpress, and rather than attaching it to it's own table in your database (and gumming it all up with cruft), it saves only a minimal representation to your post meta, and computes all the other data on the fly as needed.

Because of the above reasons, I'm unfortunately going to have to decline implementing this feature. Sorry for the inconvenience.

**Comment by JLJu** [comment]
@dsifford. It is a web-specific aspect, we will not miss this feature. In fact, we moved to a most classical layout; from our new "References page"(a list of all the references used within the whole website site) the users are able to download the RIS file. 

The light architecture of ABT is a plus.
