### ISSUE TITLE
Change the anchor text of the citations

### ISSUE THREAD

**Issue by dianne92** [dsifford/academic-bloggers-toolkit#129]
I just found about Academic Blogger's Toolkit 3 days ago and since then I'm struggling to change the anchor text from [PubMed] to be the entire actual citation?

Actual example:

Instead of:

1. E. Solovieva, K. Farrahova, A. Karneev, and D. Chipova, “[Phospholipids metabolism disorders in acute stroke].,” Zh Nevrol Psikhiatr Im S S Korsakova, 116 [1] 104–12 (2016).[[PubMed]](http://www.ncbi.nlm.nih.gov/pubmed/27045147)

I would like to be:

1. [E. Solovieva, K. Farrahova, A. Karneev, and D. Chipova, “[Phospholipids metabolism disorders in acute stroke].,” Zh Nevrol Psikhiatr Im S S Korsakova, 116 [1] 104–12 (2016).](http://www.ncbi.nlm.nih.gov/pubmed/27045147)

I ended up editing the \lib\js\reference-list\index.js file but it's out of my knowledge so please tell me how can I accomplish that.

A workaround is still appreciated ;)

Thank you!

**Comment by dsifford** [comment]
Hello again @dianne92 😄 

I like the idea. I'm sure you're not the only person who'd prefer links formatted in the way you're describing.

Let me play around for a bit and see if there's a scalable way I can add this into the plugin. More than likely it'll be the way described below:

**URL Options:**

- `whenever possible - subtle`: Insert links whenever possible using [PubMed] and (I think?) [CrossRef] (I'm forgetting how I wrote it at the moment!).
- `whenever possible - full surround`: Insert links whenever possible in the way you are describing.
- `when the citation has a visible URL`: wrap URLs in anchor tags so that they're clickable.
- `never`: Never insert links

Does this sound reasonable?

Side note: I give you credit for trying to modify the `index.js` file. You must be super patient! When I push out the plugin to WordPress.org, I shrink, minify, obfuscate, and bundle all the javascript together to keep the files as small as possible (to ensure it loads as fast as possible). Needless to say, I can't even imagine trying to edit that pile of nonsense! Kudos! 😃

**Comment by dianne92** [comment]
Hi Derek!

I have seen at least one more website using this type of citations, not sure if he's using the Academic Blogger's Toolkit plugin or not but this seems to be a reasonable way of linking to the source of citations. 

The way you presented the URL Options makes perfect sense so I'll be the first one to encourage you to make it happen.

Regarding the index.js edit, well, I only located the [PubMed] anchor text and tried to make it wrap around the whole citation - obviously, I failed :)

Thanks again for your support and for making such a great plugin.
Have an awesome day!
