### ISSUE TITLE
Wordpress stops working when ABT is activated

### ISSUE THREAD

**Issue by jourkameleont** [dsifford/academic-bloggers-toolkit#152]
**ABT Version:** 4.2.0

**PHP Version:** 5.6

**Theme:** Baskerville

**Plugin List:** Contact form 7
Custom Facebook Feed
Custom Post Type Widgets
Jetpack
Simple yearly archive

**Expected behavior:** Updated ABT yesterday

**Actual behavior:** Suddenly I can't edit posts or write new posts. The text has disappeared and everything below the Reference list widget heading on the Wordpress panel is missing (the rest of the widget as well). I have tried inactivating all other plugins and reinstalling ABT with the same result. The page looks fine and the references work as soon as I activate the plugin. 

UPDATE: updated Wordpress to the latest version and now it works!

**Console messages:**
```js
// Paste messages here
```

**Comment by dsifford** [comment]
@jourkameleont Thanks for the report. 

Can you send me a screenshot?

Also, can you open the javascript console (hit F12) and copy/paste any error messages over to here?

**Comment by dsifford** [comment]
> UPDATE: updated Wordpress to the latest version and now it works!

Just read this. Glad you were able to get it working. 👍 

I'm going to be pushing a rather gigantic update with some cool new features here within the next couple days so be prepared for that! 😄

**Comment by jourkameleont** [comment]
That's great news. Perhaps add a plain text feature then? Just a field
where you can write anything you like, like a footnote. And remove some of
the compulsory fields overall. Would be great!

2016-09-13 1:25 GMT+02:00 Derek Sifford <notifications@github.com>:

**Comment by dsifford** [comment]
@jourkameleont 

> Perhaps add a plain text feature then? Just a field where you can write anything you like, like a footnote. And remove some of the compulsory fields overall.

I'm not sure if I understand what you're asking here. 

What exactly would something like that be useful for? What separates that from just writing text in the editor without using the plugin?

Thanks for the suggestion.

**Comment by jourkameleont** [comment]
Because then it gets sorted with the other references, gets the same pop-up
window and everything. And some kinds of sources doesn't really fit with
any of the templates so then you could freestyle the entry.

And while we're at it: why did the default citation style (American Medical
Association) change från numbers in brackets to superscript? Now I can´t
find any citation style that matches the posts I've already published...

Thanks for a great plugin!

2016-09-13 15:14 GMT+02:00 Derek Sifford <notifications@github.com>:

**Comment by dsifford** [comment]
@jourkameleont 

> Because then it gets sorted with the other references, gets the same pop-up window and everything. And some kinds of sources doesn't really fit with any of the templates so then you could freestyle the entry.

What other citation type did you need specifically? I can add a "Generic" type if you think that might help. 

Here are the other available types that I do not yet have currently implemented.

- Book - Review
- Dataset
- Entry - Generic
- Entry - Dictionary
- Figure
- Generic
- Graphic
- Interview
- Manuscript
- Map
- Music - Musical Score
- Music - Song
- Pamphlet
- Personal Communication
- Post
- Review
- Treaty

> And while we're at it: why did the default citation style (American Medical Association) change från numbers in brackets to superscript? Now I can´t find any citation style that matches the posts I've already published...

In early versions of this plugin, the citation styles were only compliant for bibliographies. I've since made the compliance include the inline citations.

Two options exist if you'd like to go back to using AMA (or an AMA-like) style with bracketed inline citations:

1. Search for a similar style using the CSL style search tool [here](http://editor.citationstyles.org/searchByExample/)
2. [Create and use your own custom citation style](https://github.com/dsifford/academic-bloggers-toolkit/wiki#using-a-custom-citation-style)

**Comment by jourkameleont** [comment]
Yes, a "Generic" with no mandatory fields (but possibly several optional)
would be superb! Ok, I will look into making my own style, thanks!

2016-09-13 19:52 GMT+02:00 Derek Sifford <notifications@github.com>:
