### ISSUE TITLE
citeproc-js update (1.1.127)

### ISSUE THREAD

**Issue by fbennett** [dsifford/academic-bloggers-toolkit#153]
Hi Derek,

I've pushed a change to `citeproc-js` ([tag 1.1.127](https://github.com/Juris-M/citeproc-js/tree/1.1.127)) that might be useful to you. The new version dereferences `citation` and `Item` objects when first encountered during a processor run. There should be no change to the behaviour of the processor, but you may be able to remove the application-side dereferencing operations in your own code.

When you have a chance, please give it a try---I'm curious whether this will make the processor less quirky in async environments.

**Comment by dsifford** [comment]
Haha shoot! I just pushed the latest plugin update to wordpress about 30 seconds ago 😝 

I'll add it to the next update for sure. In the meantime, I'll play around with it locally and let you know! 

Thanks for the fix!

**Comment by fbennett** [comment]
Here's hoping it doesn't break stuff. :cold_sweat:

**Comment by dsifford** [comment]
@fbennett After looking at this, I think the issue was just that citeproc didn't like the shape of the observables. They are Maps, rather than plain objects. I ended up a few weeks ago converting out of the observable state before sending the information to citeproc and that worked for me.

The fix that you included wouldn't likely work without the change that I already made on my end because once you stringify and parse the map it will be the wrong shape.

I'm going to leave the stuff on my end as-is just to be safe.
