### ISSUE TITLE
RocketTheme plugins conflict with ABT

### ISSUE THREAD

**Issue by gumush** [dsifford/academic-bloggers-toolkit#170]
**ABT Version:** 4.4.2

**PHP Version:** 7.0

**Theme:**
RocketTheme Ambrossia 

**Plugin List:**
Rokbox 

Chrome,Edge,Firefox 

Post or page editing , Reference List box shown but nothing under. Down arrow did not changed anything. 

Errors on JS Console 

JQMIGRATE: Migrate is installed, version 1.4.1load-scripts.php:9:542
Deprecated TinyMCE API call: <target>.onNodeChange.add(..)

I removed all plugins and it works. 
I tried one by one and i found Rokbox , RokSprocket and other RocketTheme plugins  caused ABT broken.

**Comment by dsifford** [comment]
> **Plugin List:**
A lot of.

^ That is extremely relevant in this situation. I'll need to know all of them to be able to figure out what's going on.

**Comment by gumush** [comment]
Updated. 
And i guess i found the problem too.

**Comment by dsifford** [comment]
@gumush thanks for the update.

To clarify, did every "RocketTheme" plugin trigger the failure individually, or was it just one specific plugin that did it?

**Comment by gumush** [comment]
Rokbox , RokSprocket  , RokAjaxSeach trigger the failure individually.

**Comment by dsifford** [comment]
@gumush I responded to your email. Did you get that?

**Comment by dsifford** [comment]
@gumush Unfortunately, RocketThemes isn't open source and I can't physically see how they implement their TinyMCE interfaces (which is where I'm sure the issue is occurring).

My recommendation would be to delete those plugins and choose a vendor who embraces open source. 

In addition, a search in the plugin vulnerability database turned up that [several of their plugins](https://wpvulndb.com/search?utf8=%E2%9C%93&text=rok&vuln_type=) contain vulnerabilities that have not been fixed.
