### ISSUE TITLE
Bug - Will no longer add existing reference or new one after update

### ISSUE THREAD

**Issue by MattGowan** [dsifford/academic-bloggers-toolkit#197]
TypeError: this.registry.citationreg.citationById[r[0]] is undefined

**Comment by dsifford** [comment]
@MattGowan 

What version of plugin were you using when you originally created the post?

Do you have any "cited" references currently living in the document?

**Comment by MattGowan** [comment]
Hi Derek;

Thanks for responding. I was loving the plugin and I intend on donating some money to you because it’s a real time saver for me. Great work!

It was working perfect but then I was having issues with the older version I downloaded last week.  It would not allow me to insert an existing cited reference.  But it was working perfect the day before?

I decide to update to Version 4.4.7 hoping it would solve the bug.

Currently it won’t allow me to add any references or insert existing ones.  I’m attaching screenshots:

1. Add new references gives me this:


2. Adding an existing one gives me:


If you want to login to my blog and see the issue i can provide you with login info.   I am new to wordpress so perhaps i’m missing something obvious?

Thanks,

Matt

**Comment by dsifford** [comment]
@MattGowan 

Sorry for the trouble! I'd be happy to get this worked out for ya.

If you wouldn't mind emailing me login information, that would be helpful. My email address is dereksifford@gmail.com.

Can you also include those screenshots in the email? They don't attach to the issues thread if you respond via email.

Lastly, how long ago did you a) install the plugin for the first time and b) create the post that's giving you trouble? Versions in the past still had a pretty shaky/unstable API. I've since corrected those issues, but posts that were created using the older versions will sometimes give people trouble. (I'm working on correcting this!). The good news is, posts created from now on shouldn't give you any trouble (..._shouldnt_. Fingers crossed!)

**Comment by dsifford** [comment]
Confirmed bug. Fix coming next release.
