### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by someonehere15** [dsifford/academic-bloggers-toolkit#24]
I'll start by saying great job on the plugin, it is great!
I've been looking for a citation plugin to include on a prototype I need to present in two months and after a long search I stumbled upon yours. Unfortunately I still cannot use it though, one of the reasons being that it only uses PMIDs. So if I may, the following features would make it in my opinion the best reference plugin out there (and the only one for that matter):
1. First just some small details from the little I tested:
a) Maybe add an option to put a title for the bibliography section.
b) If I delete the Smart Bibliography part from the post, the Generate button is disabled unless I save the post, then I can add it again.
c) If I add a formatted reference before generating Smart Bibliography, that reference is not included in the bibliography. Maybe add an option to automatically generate smart bib if its the first time I'm inserting a reference.
2. And now the features that would make it the best plugin ever:
a. As I said, only PMID. Could you add DOI too, and retrieval through multiple sources, CrossRef, DataCite, etc. (Check the KCite plugin). IT-related papers for instance are not in PubMed.
b. Import from file, e.g. most notably bibTex, others if you like. So as an author, I can just e.g. export the references from my literature management software, and upload them onto the article through your plugin. There is a bibTex parser for php [here](http://bibliophile.sourceforge.net/) you can use, but there are others too I think.
c. Export reference option for each single one, and one file containing all. So, just to be clear, a reader sees the bibliography at the end of the post, and can download a bibTex file for each reference available, and also a single file that contains all the references. 
These killer features would make it possible for anyone to easily use citations on a blog, since they can either find it through DOI etc. or most academics have a lit.management sw already, so they can just export them. It would really become a proper reference management plugin for WP.
3. Some additional features when you get the time:
a) Option to select citation styles through using CSL, or at least some more styles available.
b) Filtering options for the bibliography (check papercite, teachpress)
c) this would get complicated, but maybe sometime in the future, a reference manager from the dashboard, to keep a list of reusable references and stuff (check teachpress). Maybe by using the Links feature from WordPress, check [here](http://blogs.plos.org/mfenner/2010/12/28/wordpress-for-reference-management/) and [here](http://alunsalt.com/2011/02/17/citation-bibliography-and-wordpress/)

I mentioned the other plugins just to give you an idea of what I mean, or how you can implement the features, I hope you don't take it as a negative feedback thing, it is quite the opposite. Your plugin is the best looking and promising so far from what I've found, and it pains me to not be able to use it. But if you could at least add the bibtex importing for authors, and bibtex exporting for readers, within two months, then I will certainly add it to my prototype, and recommend it further. 
Let me know what you think, or if I can help. Great job either way!

**Comment by dsifford** [comment]
Hi there. Glad you like it!

Good suggestions. Allow me to comment on them individually:

> Maybe add an option to put a title for the bibliography section.

You should be able to add a heading just before the bibliography using the editor on WordPress. That would achieve the same result.

**1b, 1c**: Currently thinking up a better way to handle the smart-bib. Ideally some sort of click and drag functionality that would adjust the references accordingly. It becomes tricky though due to having to also adjust the in-text citations... But stay tuned...

>  Could you add DOI too

In prior versions (I think) I had crossref integrated, but it was super unreliable which led to tons of people complaining. I think for DOI parsing it worked 1/3 of the time. I can maybe try again and see if this has changed at all though.

> Import from file, e.g. most notably bibTex

I dig that idea. I'll open an issue for this and try to get that on the next release.

> Export reference option for each single one, and one file containing all. So, just to be clear, a reader sees the bibliography at the end of the post, and can download a bibTex file for each reference available, and also a single file that contains all the references. 

This I think is a bit too niche. Most won't want this. Possibly in the future I can add it as an option, but no promised on when that would be.

>  Option to select citation styles through using CSL

That was actually my initial intention when I first made this way back when... I decided against it because the amount of files required to run a parser is astronomical. If my memory serves me correctly, it was upwards ~200 megabytes. It's almost shocking that this sort of thing isn't offered in a consumable REST API, but I suppose beggars (me) can't be choosers. 

I just checked and it looks like citeproc-js moved from Bitbucket to GitHub somewhat recently, which makes this a bit more attainable if WordPress will allow me to grab a citation format using an http request. 

Unfortunately, this likely won't be the case since WordPress is super strict with cross-origin requests. 

Having said all that, I've purposely made the data payload for every citation identical so that I could just go in and add more styles by hand as they are requested. It's really just a matter of making sure the authors are formatted correctly followed by consuming the rest of the data payload as needed. Adding new citations by hand would really only take me ~10 minutes per style.

If there are any particular styles that you'd like added, open up a separate issue per style and attach the style guidelines and I'll try and get it added for you.

> Filtering options for the bibliography

This also seems a bit niche. Again, I can maybe do this in the future, but the focus now is hammering out the necessities.

> a reference manager from the dashboard, to keep a list of reusable references and stuff

When I first started with this plugin I noticed some others that have that have [something similar](https://wordpress.org/plugins/zotpress/) to what you're describing. I was curious how they went about managing the data within WordPress and I was surprised to find that they were _really_ sloppy. On the frontend, everything looks fine, but on the backend the database gets loaded with unmanageable cruft. I opted to keep my plugin stateless for that reason.

Additionally, the other plugins that you'll see use shortcodes for parsing the references (full disclosure: I still have one shortcode that is used for the in-text citations). That's not ideal because once a user uses the plugin for a reasonable period of time, then they're stuck forever. You can't remove the plugin because it would break all your references. I'm working on thinking up a solution for removing the last shortcode that this plugin uses for that very reason.

....but anyway -- (went on a tangent there, sorry!) -- I think if I added the bibtex parser, then really this feature shouldn't be needed. I'd assume every reference management software in existence can export bibtex. That way your database will be happy, and the user can keep the concerns of reference management and delivery separated.

> I mentioned the other plugins just to give you an idea of what I mean, or how you can implement the features, I hope you don't take it as a negative feedback thing

Nope! Love the feedback. Thanks for taking the time to write it!

> could at least add the bibtex importing for authors, and bibtex exporting for readers, within two months

That's reasonable. The authors I can do for sure. The one for readers, I'll have to think about how to go about it. It'll have to be optional because I know that most likely won't want or need it.


#### Recap:
- Bibtex for authors => yes.
- Bibtex for readers => maybe.
- DOI parser from crossref => maybe if the API is more reliable
- CSL styles => maybe if wordpress allows me to grab them as needed using HTTP (low likelihood, but not totally impossible)
- Smart bibliography that doesn't suck => it's coming.
- Filtering => Not in the near future. Maybe when other important things are finished.


Thanks for the feedback. Keep me posted if there's anything else you'd like (and also your project you're working on!). 👍

**Comment by dsifford** [comment]
@someonehere15 If you can copy and paste a few examples of the bibtex you're planning on importing to #25 that would be helpful.

**Comment by someonehere15** [comment]
Thanks a lot for the quick response, I appreciate it.
To be honest, not to impose, but for my case I really need a download option. And maybe I'm wrong, but I think one of the main reasons why someone needs a bibliography, is to further use it for himself, and no better way to directly download the reference. 
Besides, if you already have a bibtex parser, wouldn't the other way be easier? especially if the poster used an imported bibtex, which means you already have the file. Even if not, you can probably easily generate a bibtex from the fields you are using.

As for DOI support, it is at least from what papers I worked with, the most used identifier. You can check what sources KCite uses, not only CrossRef. I'm not sure why users complained about this, but if e.g. the reference information is wrong because that's how it is stored in crossref, that's certainly not your fault. But it is still useful for correct references.

Anyway, thanks for your concern, I'm really looking forward to the import and export functionalities so I can use it )))

**Comment by dsifford** [comment]
@someonehere15 Closing this issue for now.. 



### Recap of recap for release 3.0.0
- [x] ~~Bibtex~~ RIS for authors
- [ ] ~~Bibtex~~ RIS for readers
- [x] DOI parser from crossref
- [x] CSL styles
- [x] Smart bibliography that doesn't suck
- [ ] Filtering (open another issue for this if you're dying to have it + include a description on how you vision it working)
