### ISSUE TITLE
Plugin not loading - insecure operation from headwayapp.co/widgets/

### ISSUE THREAD

**Issue by floaltvater** [dsifford/academic-bloggers-toolkit#244]
**ABT Version:** 4.7.2

**PHP Version:** 5.6.27

**Theme:** Twentysixteen

**Plugin List:** ABT

**Browser:** Firefox (Version: 49.0.2)

**Expected behavior:**
The "Reference List" frame shows the interface.

**Actual behavior:**
Reference List doesn't load at all.

**Console messages:**
```js
SecurityError: The operation is insecure.
	
...},n.prototype.getStorageKey=function(t){var e;return e=this.storageKey.replace(/...

https://headwayapp.co/widgets/LJ4gE7 (Zeile 9)
```
Not sure if I'm missing anything obvious. I cleared the cache, deactivated all plugins, tried on different themes, de/activated plugin.

Thanks for your help,
Flo

**Comment by dsifford** [comment]
headway is the service I use for displaying the in-app changelog... Strange. I've never had this issue. 

Can you tell me about your server? Apache host? Nginx? 

If apache, can you share with me your `.htaccess`. If Nginx, can you share your `nginx.conf`.

Thanks

**Comment by floaltvater** [comment]
Here is the .htaccess. I have the site behind a password currently for development purposes. But I have had it like this for a while.

```
AuthUserFile /path/to/.htpasswd
AuthGroupFile /dev/null
AuthName EnterPassword
AuthType Basic
Require valid-user
```

**Comment by dsifford** [comment]
Is that the entire `.htaccess` file, or did you leave out some stuff?

If it is the entire one, you're missing some important things; namely [security keys and salts](https://api.wordpress.org/secret-key/1.1/salt/), but [also other things](https://codex.wordpress.org/htaccess).

Just to be sure that this isn't a red herring, can you also confirm that the original issue is still happening? We might get lucky and it could turn out to just be a temporary network error.

Thanks

**Comment by floaltvater** [comment]
Issue still happening. And sorry, I forgot that there is an extra .htaccess in the wp directory.
```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /~altvater/private/wp_neaton/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /~altvater/private/wp_neaton/index.php [L]
</IfModule>

# END WordPress
```
The .htaccess posted previously is in the parent directory of wp, as the wp folder has several siblings that I have behind the password access as well (followed the hosts instructions on that, but always open for suggestions).

**Comment by dsifford** [comment]
@floaltvater 

Great! Glad the plugin is actually working at the very least.

Very strange though that you're having changelog trouble. If you'd be willing to give me temporary access to your site, I could check it out. Otherwise, I'm not sure what tips I can give you since I can't reproduce the issue here.

**Comment by floaltvater** [comment]
As the changelog is working in Chrome, it's most definitely a browser issue. So I don't know that you could debug it even if I gave you access, right?

**Comment by dsifford** [comment]
If it's a browser issue local to your machine, then nope, me logging in won't be helpful.

Is this issue just happening on Firefox?

**Comment by floaltvater** [comment]
I tried it on Firefox (version 49.0.2), Chrome (53.0), and in Ubuntu's own browser. And only Firefox gives problems. Already tried deactivating all plugins, but didn't change anything.

**Comment by dsifford** [comment]
And you said you tried clearing cache from all sources?

If not, can you try that. Paste this into the firefox url bar and it'll take you to that tab in the settings page: `about:preferences#advanced`

**Comment by floaltvater** [comment]
Tried it again. And updated to Firefox 50.0. No change :(

**Comment by dsifford** [comment]
@floaltvater Figured it out.

I'm 99% sure this is happening because you have some ultra-sensitive privacy settings enabled in Firefox. Specifically, you aren't allowing cross-origin cookies to be saved. 

You need to either a.) allow cookies from headwayapp.com or b.) just allow cookies altogether and use an adblocker for stubbing out tracking cookies (which is what I do -- I recommend ublock origin).

I disabled cookies on Firefox here and was able to trigger this error in the console:

![image](https://cloud.githubusercontent.com/assets/5240018/20453081/5d7c26e0-ade8-11e6-87dc-863bba6bb851.png)

Going to mark this issue as resolved since this is not a plugin issue. Feel free to keep the conversation going if needed.
