### ISSUE TITLE
Link back to citation location from Reference list

### ISSUE THREAD

**Issue by josinc** [dsifford/academic-bloggers-toolkit#255]
Please refer Wikipedia 'References' list. An up arrow just in front of the reference item takes us to that part of the article where it is cited. A link on the reference items, most probably an up arrow or just making the list numbers clickable, will be useful.

-Josin

**Comment by dsifford** [comment]
@josinc Thanks for the feedback.

The decision was made to go with interactive tooltips inline in the document, rather than have anchor links.

There are several advantages to doing it this way:
1. Having relevant references appear as the user reads allows him/her to remain engaged in his/her reading. Forcing readers to flip-flop back and forth to and from the bottom of the document is too distracting IMHO.
2. Only the references relevant to the current line are displayed. This reduces the "search" time if readers scroll to the bottom.
3. If an author has a large amount of references and he/she decides to cite, for example, reference 1 and reference 51, there's no good way to get the reader quickly to and from the references in that wide of a range without providing multiple links -- which would break the rules for a large portion of the available citation styles.

It's because of those things that I'm going to have to respectfully decline your request. Sorry for the inconvenience! Thanks again for the feedback.
