### ISSUE TITLE
Add attachments to the references

### ISSUE THREAD

**Issue by someonehere15** [dsifford/academic-bloggers-toolkit#28]
So, again: one nice additional feature would be to add an attachment link to references, e.g. by using the WordPress Media Library, or just entering a url to a file (and show a download icon to differentiate from the download reference link), in case e.g. someone wants to include a paper as a PDF with the reference. You can e.g. check out the papercite plugin that does it, just as a reference.

**Comment by sgoggins** [comment]
I agree that this is a really important feature.

**Comment by dsifford** [comment]
@sgoggins Duly noted. Thanks for the feedback.

I'd imagine that the experience would be best if you were able to insert (or upload and insert) using the native WordPress file upload utility? 

Also, would this be for manually inserted references only? Or would this also be desired for references inserted using an identifier?

Can you give me an example of how you'd ideally like this to look on the frontend? A link just after the reference? Just before? Open to all ideas / suggestions.

**Comment by sgoggins** [comment]
@dsifford : attachments are of course notoriously brutal and one of the reasons I am only slowly moving from my current site to something based on wordpress.  Drupal has long had a nice plugin for citation management, called "biblio".  My current pubs are largely found there .. here's the link just so you have a general idea; http://seangoggins.net/?q=biblio&s=year&o=desc  

The biblio plugin is here: https://www.drupal.org/project/biblio 

When I export in RIS format from Zotero (I have also used "Bookends', a mac only tool over the years), I do get folders with each file that I have in the folder. 

The ideal use case would be for the files in that directory structure to be loaded up as part of the bibliography insertion. It may even be a "create your publications page" module.

Not being a plugin developer myself, it looks like in the file "RISParser.ts"  you would need to add a case statement for the parameter "L1", which references the file and the directory structure. Then you would consider, "do I process these one record at a time"? Or, is there a way to incorporate a canonical kind of link structure in the record on the page, and then put all the files up on wordpress in the background, following that link naming structures ....  

academic-bloggers-toolkit/lib/js/utils/RISParser.ts 

Here's an example of one record with a file in my own Zotero export : 

TY  - JOUR
TI  - Connecting performance to social structure and pedagogy as a pathway to scaling learning analytics in MOOCs: an exploratory study: Measuring learning performance in MOOCs
AU  - Goggins, S.P.
AU  - Galyen, K.D.
AU  - Petakovic, E.
AU  - Laffey, J.M.
T2  - Journal of Computer Assisted Learning
DA  - 2016///
PY  - 2016
DO  - 10.1111/jcal.12129
DP  - CrossRef
VL  - 32
IS  - 3
SP  - 244
EP  - 266
LA  - en
SN  - 02664909
ST  - Connecting performance to social structure and pedagogy as a pathway to scaling learning analytics in MOOCs
UR  - http://doi.wiley.com/10.1111/jcal.12129
Y2  - 2016/05/01/17:16:49
L1  - files/2498/jcal12129.pdf
ER  -

**Comment by dsifford** [comment]
@sgoggins First, I'd like to mention that I humbly bow to your computer science prowess. Your credentials are certainly impressive!

But anyway.... You make good points. The only issue that I foresee is that (to my knowledge) I don't believe I'd be able to consume the files during RIS import using the path specified on the L1 line because the plugin only "sees" the paths that are available to it on its own server.

I could be wrong, but off the top of my head the only way I'd be able to consume files is if they are sent through as file blobs (similarly to how the RIS file is sent through), which means each individual file would likely have to be passed in one at a time.

I'll look into how biblio does it in the near future. Perhaps they know something that I don't!

Also, if you have any suggestions/tips I'd be glad to hear them!

**Comment by sgoggins** [comment]
oK ... I have never written wordpress plugins and I know from those who do that there are limitations of sorts. and @dsifford ... one should not bow to my computer science prowess ... I'm a hack of a coder and spend more time writing words than code these days ... but I can remember when java was launched, so I am at least old ...

I have an idea for a hack that might not be too much work, and if you get the code to do it, I'll do a youtube video and explain it .... 

1. On load, detect the WP User's default upload path for files/media (hoping this is visible)
2. For any file with "L1" specified, create a PDF link (ideally with the PDF icon) on a new line just below the rest of the citation. 
3. That link should point to upload path/pdffilename.pdf 
... in the example above, it would point to "path/jcal.12129.pdf"  

I took the liberty of hacking the text for the previous example. So , this is what it would actually look like:
<li>Goggins, S. P., Galyen, K. D., Petakovic, E., &amp; Laffey, J. M. (2016). Connecting performance to social structure and pedagogy as a pathway to scaling learning analytics in MOOCs: an exploratory study: Measuring learning performance in MOOCs. <i>Journal of Computer Assisted Learning</i>, <i>32</i>(3), 244–266. <a href="http://doi.org/10.1111/jcal.12129" target="_blank">http://doi.org/10.1111/jcal.12129</a><br/><a href="http://datascience.goggins.com/wp-content/uploads/2016/05/jcal12129.pdf">PDF</a></li>

It does work, as you can see on this page:
http://datascience.goggins.com/7-2/?preview_id=7&preview_nonce=65ecccb142&preview=true 

Then the user would need instructions for uploading the files one by one, or as a zip file.

For some people, just doing the hack I outline above is enough ... my paradox of nominal success is I have 117 ish publications ... so, a lot more work ....

**Comment by dsifford** [comment]
@sgoggins In theory that sounds good. But the issue would be there are (purposeful) limitations in place preventing that sort of thing from happening (to my knowledge -- if I'm wrong don't be afraid to shoot me down! Hah). What I mean is, I wouldn't be able to just reach in and grab files (even if given the path name) without more deliberate action taken by the user. Otherwise, what's to stop people from stealing sensitive data from you as they load up a webpage?

I could probably manage taking a compressed set of files (gzip, zip, etc) and then walking through them. However, that's an extremely rare (or rarer-than-normal) use case. 

What I had in mind was to use WordPress's baked-in media manager to allow file upload and attachment one at a time (similarly to how the peer review boxes use it for photos). I was thinking of possibly adding button or menu to the reference list where you could just click a reference, then hit the "attach" button and insert a single attachment where needed.

Would that be an acceptable middle-ground? If not, I'm still open to discussing further. I think the conversation will become easier for me to wrap my head around once I actually start working on this.

PS: I'm unable to access the page you linked to since I don't have admin privileges at your site.

**Comment by dsifford** [comment]
Having said all that........ 

How does Zotero do it? Do they allow you to import RIS _with_ attachments? Can you explain the flow of that process?

I might have to call the programming supergenius/zotero mastermind/nicer-than-the-average-bear @fbennett into this conversation. I'd imagine he'd be able to share a trove of helpful information on this.

**Comment by fbennett** [comment]
I'm don't know the translator/import end of things in Zotero very well, but on a quick check, RIS supports round-trip export and import of items with attachments. The export creates a directory containing the RIS object with the item metadata, and a ./files subdirectory containing the attachment files. The L1 link(s) in the RIS data are relative paths, starting with 'files/...'. I'm not sure whether an absolute path there would be treated as valid, but I reckon not, for the reasons given by @dsifford.

I wonder, though. If ABT is mainly about authoring for the Web, you could use the API of one or more of the reference managers (Zotero and Mendeley, and I think EndNote also?) to reflect the user's library (or a subset of it), and leave this kind of heavy lifting to the other tool.

**Comment by dsifford** [comment]
> you could use the API of one or more of the reference managers (Zotero and Mendeley, and I think EndNote also?) to reflect the user's library (or a subset of it), and leave this kind of heavy lifting to the other tool.

That sounds ideal to me.

Thoughts @sgoggins? @someonehere15?

**Comment by someonehere15** [comment]
Hey sorry just catched up. 
First of all, I think the site content would be better structured if you do use the wordpress native media library and not leave the files unlinked to wp because they may remain orphaned once not used anymore or you plugin disabled for some reason. If you can find a way to combine both using the RIS link and adding it to the library, then its OK.
On the top of my head, you can for instance upload a whole folder, or zipped as you said, including the RIS, and match the RIS to the files, but I think you can do that in the future. For now you can just add an option for each reference e.g. on the widget to attach a file to it, which is uploaded by wp library. 

As for the API, im not sure I understand it right, but something similar does the Mendeley plugin for example, but I think that would just be something like embedding the managers library on the site, which is not this Plugins purpose. Unless I got it wrong, maybe you mean something else? Besides, the author may not necessarily have a Web library on one of the managers to link to. But I think I misunderstood?

**Comment by dsifford** [comment]
Closing this for now since I don't anticipate getting to this in the immediately foreseeable future. I'll come back and reopen if/when this feature aligns itself with the project trajectory.
