### ISSUE TITLE
Add import references by file URL

### ISSUE THREAD

**Issue by someonehere15** [dsifford/academic-bloggers-toolkit#29]
Hi again, 
So as discussed, it would be nice to provide an option to enter the URL of a reference file (RIS in this case) and directly import the references from there without uploading the file locally.

**Comment by dsifford** [comment]
Can you give me an example of where this url would come from? Dropbox or something? Any chance you can provide one for me to play with?

**Comment by someonehere15** [comment]
Oops, sorry, just saw this. Although this is not a necessity like I said, it is just something additional that would simply avoid locally downloading the file, so no worries about it.
 What I mean is something like citeulike.org for instance, where there are libraries, users, etc., and you can download files directly. For example:
http://www.citeulike.org/author/Krcmar:H is an author page. You can see there that there are many export options. But even without opening the page, the url for RIS has this structure:
http://www.citeulike.org/endnote/author/Krcmar:H
So you just add "endnote" and the file is generated and downloaded. In our case, I would put this URL in your plugin and it downloads everything from this author.
I hope it is clear now. But maybe dropbox, etc. is also not a bad idea, although it's the same to you as long as the link is accessible right? You don't need any fancy features, to connect with dropbox or something, that is absolutely unnecessary.

**Comment by dsifford** [comment]
@someonehere15 I'm not able to make the URL you provided open to exactly RIS format. Can you clarify on this?

**Comment by someonehere15** [comment]
what do you mean? it gets download perfectly for me. You click the second link and a ris file downloads.

**Comment by dsifford** [comment]
Correct, but that's precisely what I don't need in order to programmatically extract it. If it rendered in its own page as plain text, id be able to consume it using a simple HTTP request. It becomes trickier if its a file glob (as is this case)... 

I might be able to figure out how to extract from citeulike, but that would become a slippery slope in that if then have to do it for more individual sites as they are requested. I'm thinking this probably isn't going to be worth the time investment being how simple it is to just download to file and upload.

**Comment by someonehere15** [comment]
No problem, it was just an idea anyway, a bonus feature, but not at all required.

**Comment by dsifford** [comment]
Keep the ideas comin!
