### ISSUE TITLE
Adding compatibility with Ckeditor

### ISSUE THREAD

**Issue by carot2016** [dsifford/academic-bloggers-toolkit#302]
Hello, a suggestion that Academic Blogger’s toolkit can work with CKeditor plugin in WordPress.

Thank you

**Comment by dsifford** [comment]
@carot2016: Infrastructure is now in place to add support for this. 

Let me know if this is still something you're interested in and what version of CKEditor you're using. (Preferred version is CKEditor 5).

**Comment by carot2016** [comment]
Hello, for sure we are interested but CKEditor for WordPress is only in Version 4.5.3.3.
Is version 5 compatible with WordPress?

**Comment by dsifford** [comment]
Assuming you're talking about [this plugin](https://wordpress.org/plugins/ckeditor-for-wordpress/), it looks like the CKEditor team stopped maintaining the plugin over 2 years ago. I'd have a tough time working with that plugin because of how dated it is.

Additionally, it looks like the plugin itself has a [few listed vulnerabilities](https://wpvulndb.com/search?utf8=%E2%9C%93&text=ckeditor) which makes its use in general unsafe until the maintainer can fix.

Ideally, I'd be most comfortable working with the latest version of CKEditor. It seems a bit strange to me that the CKEditor team would just abandon their wordpress plugin being that it has over 70,000 active installs. Maybe you can reach out to them and get them to update?

**Comment by dsifford** [comment]
That all said, I'll look into it when I get time. If the editor's API is the same between versions then it might still be feasible.

**Comment by dsifford** [comment]
Due to WordPress merging over to the new Block Editor, I'm no longer going to consider this feasible.
