### ISSUE TITLE
Changing the inline footnote style

### ISSUE THREAD

**Issue by Amith211** [dsifford/academic-bloggers-toolkit#319]
Hi,
Let me start by thanking the devs for this brilliant plugin; I was genuinely surprised to see that OSCOLA was supported.

I have noticed that the current implementation is not quite in compliance with the standard. OSCOLA uses a superscripted inline footnote style (i.e example.<sup>1</sup>), however,  it currently being displayed as [1]. 

What's the best method of implementing said style change?

Cheers

**Comment by dsifford** [comment]
Hi @Amith211,

(Correct me if I'm wrong @fbennett)

I believe that is a limitation of the citation processor. Currently, the only data that is given to the parser for footnote-type citations is position, so the only way to handle footnotes in general was to aggregate a common style (in this case the `[1]`, `[2]`, `[3]`, ..., `[n]` style).

**Comment by stewartfoss** [comment]
I think I'm dealing with a similar (maybe the same) issue. I am citing using Chicago Manual of Style. To my understanding of the style, the footnote should be referenced in a superscript, yet it is being inserted in square brackets ie. [1]. I noticed that there are other styles in the plugin that use superscripts and I'd love to know where to make a change so that Chicago uses a superscript.

**Comment by dsifford** [comment]
cc: @fbennett

**Comment by fbennett** [comment]
What @dsifford says is correct. The citation stylesheet does not have control over the formatting of footnote markers.

**Comment by stewartfoss** [comment]
So where does that come from? When I choose American Medical Association from the Wordpress plugin I get superscript footnote markers, but when I choose Chicago Manual of Style I get square brackets. I'm not suggesting it is a CSS thing, but is there a way (short of editing plugin files) to get it to display the other way?

**Comment by dsifford** [comment]
@stewartfoss The plugin generates the footnotes and citations using [CSL xml](https://github.com/citation-style-language/styles) as its "recipe book". CSL does not specify the format for footnotes like it does for inline citations so in order to avoid potentially clashing with the thousands of other styles, the `[n]` format was chosen. There's no way to change this without changing the internal implementation of the plugin which is not an option at this point (because, again, the current format avoids clashes with styles that use superscript inline citations AND footnotes).

The long-term solution would be to have CSL carry along information about the style of the footnotes, but that would have to be taken up with the CSL team.

**Comment by stewartfoss** [comment]
Maybe I'm not understanding what you are saying here, so I appreciate your patience in trying to convey this to me. What I'm hearing is that you opted to have all formats use [1] style for footnotes. Yet, when I select American Medical Association I get superscripts. So where are the instructions for American Medical to use superscripts coming from? You say it is not in the CSL recipe, then the plugin code must where this happens, right? So why superscripts for American Medical and brackets for Chicago?

**Comment by dsifford** [comment]
Sorry for the confusion. The AMA format gets superscripts from the CSL recipe because they are inline citations, not footnotes.

Only footnotes styles are unspecified.

**Comment by stewartfoss** [comment]
Ok, after hearing your description and looking back at the code generated on my page I think I understand the difference. What I saw at the bottom of the page and thought were footnotes when I selected AMA, are actually a bibliography. The inline citations come in the form of a superscript number and a modal that displays the content of the inline citation? Correct?

**Comment by dsifford** [comment]
That's correct
