### ISSUE TITLE
Enable/Disable Per Post Type

### ISSUE THREAD

**Issue by charitablehumans** [dsifford/academic-bloggers-toolkit#325]
I'd like the ability to disable the citation meta box from appearing on all custom post types and only enable it for blog posts or other custom post types.

**Comment by dsifford** [comment]
@charitablehumans Sorry for the long radio-silence. 

I'm going to add the ability to filter the disabled post types so that users can extend the disabled post types in the next major release.

I've already added documentation for this here: https://github.com/dsifford/academic-bloggers-toolkit/wiki/Developer-Hooks#abt_disabled_post_types

You can feel free to add the hook into your `functions.php` file now and when version 5 finally gets released, those changes will automatically just work.

Hope you find that helpful. Thanks for the feedback.
