### ISSUE TITLE
Global citation pool

### ISSUE THREAD

**Issue by mredaelli** [dsifford/academic-bloggers-toolkit#335]
I often have to quote the same documents in several different posts.

It would be very convenient not to have to recreate the entry in every post. Is it possible to have a global repository of items that can be cited from all pages/posts?
Of course one way to do it is to import the same file in every document, but then again, it's one step more :)

**Comment by dsifford** [comment]
Hi @mredaelli 

This has been asked in the past and it's really one of the only things I'm at a firm "no" on. Reason being: Adding that feature will allow users to use wordpress as a reference manager of sorts, rather than use a true reference manager to manage their academic references/papers (e.g. Zotero, Mendeley, EndNote, etc).

So, in an effort to avoid enabling the less than ideal practice of managing references inside wordpress, I'm going to remain firm on this. Hope you can understand!

My suggestion to you would be to import your commonly cited references into its own little folder inside Zotero and then import that little folder using the import tool on any page that you might need them.

Thanks for the feedback.

**Comment by mredaelli** [comment]
I see your point, but the problem with that approach is that if I have imported the file in, say, 5 posts, and I find out that there was an error, I have to go back to every post and manually update the entry (reimporting the file doesn't fix the entry, but duplicates it).
This is very inconvenient and unintuitive - the entry is "the same".

**Comment by dsifford** [comment]
Good point. That does make things a bit more inconvenient. 

However, another issue with adding this functionality is that it would be both difficult to implement and hard to maintain. Because of those things, I'm going to stay firm on this for now.
