### ISSUE TITLE
Editor Disappear after activate

### ISSUE THREAD

**Issue by jmvillatoro** [dsifford/academic-bloggers-toolkit#370]
**ABT Version:** 4.11.2

**PHP Version:** 7.0

**Theme:** Newspaper 8.1

**Plugin List:**
- CM Tooltip Glossary Pro+
- Hummingbird Pro
- SG Optimizer
- tagDiv Composer
- tagDiv Social Counter
- TinyMCE Advanced
- WP Defender Pro
- WP Smush Pro

**Tested with just ABT activated too.**

**Which web browser are you using (including version)**
Opera: 48.0.2685.39 (PGO)
Tested in Firefox, Edge, Vivaldi and Chrome too, same problem.

**Expected behavior:** Can edit and see the text.

**Actual behavior:** Can't edit text, when I activate the plugin, my text editor disappears and the text in the content field too.

**Console messages:**
```js
// Paste messages here
Uncaught ReferenceError: _ is not defined
    at HTMLDocument.<anonymous> (post.php:2904)
    at i (load-scripts.php:2)
    at Object.fireWith [as resolveWith] (load-scripts.php:2)
    at Function.ready (load-scripts.php:2)
    at HTMLDocument.K (load-scripts.php:2)

**Comment by dsifford** [comment]
@jmvillatoro Thanks for the report. 

Have you disabled all your other plugins and ensured that it is ABT that is causing this issue? By the looks of it, it appears that it might be a plugin conflict because the error you pasted is being thrown by `load-scripts.php` rather than one of ABT's plugin files.

From your list, the plugins that I know should work are TinyMCE Advanced and WP Smush Pro... Not sure about the others.

Also, can you please post a screenshot of the issue?

Thanks in advance

**Comment by dsifford** [comment]
@jmvillatoro Scratch that... I think there's a problem with TinyMCE Advanced. Another user reported something similar to this as well and they also have that plugin activated.

**Comment by jmvillatoro** [comment]
@dsifford Hello, yes I tried with all the plugins disabled, and just with ABT. I will try again, and post the update.

**Comment by jmvillatoro** [comment]
![opera captura de pantalla_2017-10-18_005516_comparteciencia cl](https://user-images.githubusercontent.com/7306776/31747801-485ef346-b445-11e7-9596-874b44a31c06.png)
![opera captura de pantalla_2017-10-18_204508_comparteciencia cl](https://user-images.githubusercontent.com/7306776/31747803-504074fe-b445-11e7-825e-6b86f56bb045.png)

**Comment by dsifford** [comment]
Hm.... Very strange. 

It looks like you're possibly using SiteGround and their caching? I've had issues specifically with SiteGround's cache in the past serving stale files. Can you try clearing all of the cache on your server and see if that helps?

Sorry for the trouble. I'm confident we can get this sorted out 👍

**Comment by jmvillatoro** [comment]
I tried this with SG Cache off. When I activate the plugin and try to edit an article or a page, the site gives me error 502 sometimes. After deactivating ABT, I can edit again.

This is happening after one of the last updates of ABT;  I really don't know last version stable on my site (no articles added in a few months, the site is in development). 
The strange thing is before the last updates of ABT, the plugin was working great, and I have the same pack of plugins installed (even the cache was on).

**Comment by dsifford** [comment]
@jmvillatoro Disabling the cache plugin will not clear any cache that already exists. The problem (usually) is that cachepress caches the last version of the plugin and when you load up the page it tries to send files that don't exist anymore after updating.

Could you try manually clearing your site's cache (if you're using siteground, that'll have to be done in cpanel) and then try again just so we can completely rule out the cache as being the issue?

Thanks in advance.

**Comment by jmvillatoro** [comment]
@dsifford Yes, when I say I deactivate the cache, includes clean the cache and deactivated from SG cpanel (the plugin was already disabled). The problem remains after that action.

**Comment by jmvillatoro** [comment]
Some images with all the plugins off, except ABT, Twentyfifteen theme and cache cleared and deactivated from cpanel, no CloudFlare connection.

![pluginsoff](https://user-images.githubusercontent.com/7306776/31770624-356e8b10-b4af-11e7-861b-df5b08f57a2e.png)
![editorbug](https://user-images.githubusercontent.com/7306776/31770629-37ad4b3c-b4af-11e7-82d0-f58c045ea8e9.png)

**Comment by dsifford** [comment]
@jmvillatoro Hm... Super strange.

Another user who is also on siteground has the exact same issue and I'm not quite sure what could be going on.

Are you on WordPress Multisite?

**Comment by dsifford** [comment]
Update: Just checked with the other siteground user that was having a similar problem as you and they said that clearing the cache also did not work initially, but hours later the plugin began working without any other action. 

So their problem was indeed cache. Let me know if yours resolves similarly. If not, we'll keep troubleshooting.

**Comment by jmvillatoro** [comment]
Ok, will wait a few hours more, the cache was cleaned and the cache plugin was deactivated. When I check again I will post the update (ABT active).

**Comment by jmvillatoro** [comment]
Nothing, same thing.

**Comment by dsifford** [comment]
Any chance you can create me a temporary login on your site with Author privileges so I can check it out?

**Comment by jmvillatoro** [comment]
@dsifford Sure, tell me where I can send you the login.

**Comment by dsifford** [comment]
dereksifford@gmail.con

**Comment by jmvillatoro** [comment]
Details sent

**Comment by dsifford** [comment]
@jmvillatoro The plugin scripts aren't being loaded at all on the post edit page of your blog. The only thing that I can think would cause this to happen is stale cache (particularly from siteground).

Without the scripts being loaded the plugin cannot work.

I'm 99% certain this is exclusively a siteground cache issue since I've had similar issues in the past. The solution would be to contact siteground support, have them manually delete all cache files stored by their cache plugin, delete their cache plugin, and use a better caching solution (I recommend w3-total-cache).

There's nothing I can really do to fix this on my end unfortunately

**Comment by jmvillatoro** [comment]
@dsifford Ok, thank you very much for your time and help. I will contact SG support and see if they can manually erase cache files.

**Comment by jmvillatoro** [comment]
Question, in which version do you add the Headway Tooltip?

**Comment by dsifford** [comment]
Headway was added in version 4.7.2 (~1 year ago)

**Comment by jmvillatoro** [comment]
@dsifford I got an answer from SG : 
"I have been able to replicate it, but it appears that a plugin is conflicting with it causing JavaScript errors, there is nothing on our end caching it or preventing it from working.
You can see the errors in your browsers error console:
https://prnt.sc/gzv536
I suggest contacting the plugin developer again or hiring a professional developer that could assist you with fixing this.
If you have any other questions or concerns let us know and we will be happy to help.

Best regards,"

Well, I think the only solution for me or the SG customers using this plugin, is use another version (old version).
Do you have some old version (one or more) so I can test where the problems arise, would be great. Thanks for all.

**Comment by dsifford** [comment]
@jmvillatoro The siteground rep is not correct. That error that he/she is speaking of is unrelated to this plugin. Additionally, the source of the error itself is encapsulated in a way that does not interfere with the execution of other plugins.

From experience speaking with SiteGround reps, I will say that the majority are not proficient in understanding how the web actually works.

The issue is that files are not being loaded on the post edit page. The only thing that I can imagine that would interfere with this from happening is their (siteground's) mediocre caching.

**Comment by jmvillatoro** [comment]
@dsifford I ask to escalate the report to advance support, hope they can help me with this.
I clone my site in one of my other hosting accounts (inmotionhosting) and the ABT plugin works like a charm there, so as you say, this is an SG problem with this particular plugin. I don't know in which version this issue starts.

**Comment by dsifford** [comment]
@jmvillatoro If the problem is isolated as a Siteground cache problem, then you unfortunately won't be able to just simply roll back to a previous working version. Your cache is going to be stuck permanently on a broken one until SG can get it cleared out.

Crossing my fingers for you that SG can get it resolved. Like I said before, I use w3-total-cache on my site which works well. Also, another great option is wp-super-cache (which is made by WordPress's parent company Automattic)

**Comment by jmvillatoro** [comment]
@dsifford Well after many tickets, the Advanced Technical support from SG fix the problem, here is the workaround in case some other user of ABT is hosted there.

"I have managed to fix the issue by altering the SubstituteMaxLineLength and LimitRequestBody variables of the web-server. The rules have been added into the ~/public_html/xxx/.htaccess file. 
Please, clear your browser's cache and verify the results on your end.
Dimitar Petrov Dimitrov
Senior Technical Support"

**Comment by dsifford** [comment]
@jmvillatoro 🎉 🎉 🎉 That's great news!

Thanks for chiming back with the solution. This will be helpful I'm sure to a lot of others.

Do you happen to know what those variables were set at to begin with on your server?

**Comment by jmvillatoro** [comment]
@dsifford Sadly I have no clue where he changes those parameters, is a managed WP account, so my access is limited. I only see the lines in my htaccess file.
`SubstituteMaxLineLength 10m
LimitRequestBody 10240000`
