### ISSUE TITLE
Citation block makes adjacent misbehave

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#372]
![temp](https://user-images.githubusercontent.com/17968340/31741850-9e415302-b40a-11e7-90fb-4ada16b293c4.png)

In this image I just added references 122,123. The text boxed in red cannot be clicked on. The cursor will not select the clicked location. I can select any other text though.  So for example, if I click on the boxed text, the cursor will just keep on blinking in it's current position, wherever that happens to be. 

There is a workaround though. See the next 2 shots:
![image](https://user-images.githubusercontent.com/17968340/31742046-3aa1cb5a-b40b-11e7-8293-ed8a27e5901b.png)
I select some text.

![image](https://user-images.githubusercontent.com/17968340/31742066-4c75cd36-b40b-11e7-8cf7-991dd8e07427.png)

I press the right arrow. Now the cursor is blinking in the previously unaccessable text, and I can type there.

**Comment by dsifford** [comment]
Likely the issue is that in the HTML side of your editor there's fragmented html that encapsulates where your cursor was and the content of the noneditable block after your citation insertion.

Issues like this are unfortunately impossible to guard against. The solution to it should it happen in the future is to switch the the html editor and make sure the span tag surrounding your citation does not include the other text...

So for example:

This....

```html
<span class="abt-citation mceNoneditable"><sup>1, 2<sup> Some other text that is caught</span>
```

Should be converted to this.....
```html

<span class="abt-citation mceNoneditable"><sup>1, 2<sup></span> Some other text that is caught
```

Unfortunately, the larger and more complex your document becomes, the more prevalent these types of issues will likely become.
