### ISSUE TITLE
Questions outside the scope covered in Wiki

### ISSUE THREAD

**Issue by necxelos** [dsifford/academic-bloggers-toolkit#375]
I have a few questions regarding functionalities of ABT. Hopefully this is the right place to ask them, as You stated in wordpress plugin page that no questions will be answered there.

a) Is there a way to have bibliography include uncited items? Or a way to have separate un-cited bibliography?
b) Is there a way to add header title to static list?

Both of those are usefull in case of popular science articles instead of strict scientific articles in which case bibliography serve more of a "suggested readings" purpose than source of what was written in the article.

c) Is there a way to disable on-click event on citation inside the text, creating pop-up with related position in bibliography? I'm going to use tooltips intensively on my blog and having citations click-able too will create certain degree of clutter.

d) I found a strange effect. Adding title to regular bibliography in settings, didn't actually add this title on the front end until I entered post and updated it (just clicked the button). Might not be a big issue before site goes live (my case), but if someone ever decides to make changes on live site later it will become a major issue (going through all published posts one-by-one just to apply one global change feels like a no-go).

Thanks in advance for Your answers
Lucas

**Comment by dsifford** [comment]
No problem. Questions are fine here.

a.) You would need to create and insert static publication list for that (as I think you've already found out given your next questions).

b.) There is not a way to give the static lists a permanent header, but that's by design. The static lists are meant to be flexible. So you'd need to just add the header using the WordPress editor.

c.) Not sure I fully understand what you're asking here. Are you wanting to just permanently disable the tooltips?

d.) That's a known weakness of using the heading option on the options page, rather than just adding one using css. There's a bit of a trade of doing it each way.

1. **Title using "heading" option**:
  - **Pro**: Accessibility is highly improved for visually impaired users visiting your site who rely on screen readers because the hard-coded heading element also gives the heading a semantic meaning to the screen reader.
  - **Con**: Headings are added to the post content directly. In order to make them to historic posts, you'd need to open each one and edit it individually for it to take effect.
2.  **Title using CSS**:
  - **Pro**: Titles are automatically applied to every post, old and new, without any further action needed.
  - **Con**: No semantic meaning is given to the heading so screen readers will often miss it.

Hope that helps.

**Comment by necxelos** [comment]
c) Yes I want to permanently disable tooltips.
d) How would I add title to the bibliography using just CSS?

**Comment by dsifford** [comment]
c.) You should be able to do that by adding `pointer-events: none;` to the `abt-citation` class selector in css.

d.) https://codepen.io/dsifford/pen/KyzweK?editors=0100

**Comment by dsifford** [comment]
Haven't heard back from you. Assuming my comment above resolved your question. 

Closing this issue. Feel free to reopen if you're still confused about something.
