### ISSUE TITLE
IE tooltips

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#38]
I now have access to a computer with IE, and tooltips do not display.

**Comment by metallikat36** [comment]
FYI, I tested the reordering of references pretty heavily and it all works fine. Only feature I am personally still desiring is collapsible list, but the plugin is totally functional as is.

**Comment by dsifford** [comment]
@metallikat36 I've decided to not concern myself with a browser that will soon be consumed completely by Edge. 

IE as a whole has a ~5% global usage rate (which is shockingly higher than I would have guessed). If they are comfortable with a horrible baseline browsing experience, than no tooltips for them!

I might add a polyfill to let IE users know that they need to [get a better browser](browsehappy.com) or something along those lines, but not gonna worry about prioritizing it.

Glad to know the reordering is working well. I'm working on the optional collapsible list now actually. Shouldn't take terribly long to complete. I'm also working on adding better end-to-end test coverage so that might delay it some. But sit tight, it's coming.

**Comment by metallikat36** [comment]
Agreed about IE.
