### ISSUE TITLE
in-text citations don't wrap?

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#398]
**ABT Version:** 4.12.0

**PHP Version:** 5.6

**Theme:**GeneratePress

**Plugin List:**
-  Very Simple Event List
- Child Theme Configurator
- TablePress
- bbPress
- Sidebar login
- Paypal Donations

**Browser:** Firefox 57

**Expected behavior:** Citations in the text wrap.

**Actual behavior:** If a series of in-text citations is wider than the window, the rest is simply cut off at the window edge.  If an image narrows the space available, the citation and following text jump down below the image (see attachment).

**Console messages:**
```js
Note: this only appears if all other plugins are deactivated (then popups don't work). 
With others activated, this doesn't appear (and popups work).
ReferenceError: jQuery is not defined
[Learn More]
frontend.ts:1:6

```
![screen shot 2017-12-23 at 1 04 24 pm](https://user-images.githubusercontent.com/6004417/34322397-5cfe9ea6-e7e3-11e7-9c47-f1d90db8e540.png)

**Comment by dsifford** [comment]
Thanks for the report. Do you have a link to the affected page that I could check out?

**Comment by glorious1** [comment]
Yes indeed.  The page in the screenshot is here
http://109.73.239.174/~cookand3/forestpathology.org/air-pollutants/

and that thank you test page has it without an image:
http://109.73.239.174/~cookand3/forestpathology.org/thank-you/

Sorry to keep loading you up with issues!

**Comment by dsifford** [comment]
Ah, now I remember why I explicitly made citations non-wrapping. It becomes much more difficult to calculate where the tooltip should be placed if the citation spans more than one line because both the natural width and height of the citation are variably skewed, depending on how much the text wraps.

Obviously, this is a problem with long in-text citations. I hadn't considered that. 

I'll work on improving the tooltip rendering so that text will be able to wrap naturally. 


> Sorry to keep loading you up with issues!

Please, keep them coming! I appreciate the feedback.

**Comment by glorious1** [comment]
Ahh, I see.  Well I could always switch to number citations, which would never need to wrap.  They are not so common in my field, but certainly less cluttered, and with the tooltips, you don't really need the full citations.

**Comment by dsifford** [comment]
Found a much simpler fix than I originally anticipated. This should be resolved on the next update. If not, let me know.
