### ISSUE TITLE
Make tooltip links clickable

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#4]
Hi.  First of all, thank you for this plugin.  It is the only citations plugin that I could get to work at all on my site.  I am rather dumbfounded that citations plugins are virtually non-existent.  I would have thought it is a basic requirement that thousands of sites would be using.  I guess not...I also appreciate the convenient CSS override which has allowed be to easily style the citations into superscripts. 

Anyway, I am going to start a few threads with my suggestions, I hope you can possibly make them happen.

Suggestion 1:  Make tool tips clickable.  For an example, look at a wikipedia article.  The tooltips allow you to click a link that sends you to an external url.  I would dearly like this.  It is just more user friendly.  Otherwise you have to scroll down to to the references, click the link there, then scroll back up to the article to continue reading where you left off.  So once more, what I am suggesting is that the PMID link in the tooltip be functional.

Rlelated Question:  Are the anchor links (inline citations) intended to scroll down to the references when you click on them?  They don't do anything on my site.  This is actually fine for me, and is the way I would want it to stay, if the tooltips were clickable.  Then there wouldn't be any need to want to scroll down to the references with a click.  Though since the word "anchor" does imply clicking it should do something, I am just curious about whether or not I have a bug in this regard.  This is just a question, rather than a suggestion for a change.  

More threads coming...

**Comment by dsifford** [comment]
@metallikat36 Glad the plugin works well for you. Allow me to respond to your questions in order:

> the PMID link in the tooltip be functional.

I tossed this idea around as well while putting together the recent update. I think it's totally valid. Your suggestion was just enough for me to change my mind on it.. I'll work on getting an update pushed out soon.

The one proviso of having functional links in the tooltip is that the tooltips will have to be (at minimum) destroyed on click outside of the tooltip. As of right now, it's set up so that they are created and destroyed on hover and mouseout.. There's no way to maintain that functionality while having clickable links since moving your mouse to the link would cause the tooltip to destroy itself. (I might be able to figure something out though)...

> Are the anchor links (inline citations) intended to scroll down to the references when you click them?

Nope, that was the old functionality. Actually, the inline citations aren't even `<a>` tags anymore. They're `<span>` tags with a pointer hover effect.

> Though since the word "anchor" does imply clicking it should do something, I am just curious about whether or not I have a bug in this regard.

Where is it you see the word anchor? Perhaps I forgot to edit something after making the recent changes. Documentation I assume? Thanks for the tip!


Looking forward to your other suggestions. Keep 'em coming! :+1:

**Comment by metallikat36** [comment]
- The word anchor appears by the CSS override box in the wordpress plugin settings page.  

- Not sure I understand the problem you are describing about maintaining the hover/mouseout functionality.  In any case, perhaps some kind of trick can be gleaned from Wikipedia tooltips, which are created and destroyed on hover and mouseout, yet they don't get destroyed when you hover on the link. 

-Or maybe there is some kind of time delay setting that could be implemented?  Like make the tooltip disappear1 second after mouseout?  If such a thing existed, it could give enough time to click the link.  

-  If you do need to go with destroy on outside click, then also consider whether or not it is best to make it appear on click a well for consistency.  I'm not sure I have an opinion about that yet.

**Comment by dsifford** [comment]
> The word anchor appears by the CSS override box in the wordpress plugin settings page.
Ah, cool thanks for letting me know

> perhaps some kind of trick can be gleaned from Wikipedia tooltips
I think I can probably put something together similar to Wikipedia. Good idea.

**Comment by dsifford** [comment]
@metallikat36 Just finished this. I'll be including it in the next plugin update (See [milestone 2.3.0](https://github.com/dsifford/academic-bloggers-toolkit/milestones))

I think you'll really like what I came up with :+1:
