### ISSUE TITLE
TypeError: e.people is undefined / TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by tosokuzma** [dsifford/academic-bloggers-toolkit#405]
**ABT Version:** 4.12.1

**PHP Version:** 5.6

**Amory:**

**Plugin List:**
WP Clean Up
WP PageNavi...

**I am just trying to add References via the GENERIC (Note) function, which worked perfectly fine in the past but stopped working 3-4 days ago.**

**When I try to add a reference, one of the above error messages appears depending on which browser I am using**

**Comment by tosokuzma** [comment]
PS I updated to the latest versions of Edge, Chrome and Firefox just to make sure it is not a related error.

**Comment by tosokuzma** [comment]
Firefox ("TypeError: e.people is undefined), Chrome ("TypeError: e.people is undefined") - updated to newest version in each case

**Comment by dsifford** [comment]
Thanks for the report.

This is related to #401. The fix for this specifically was already completed, but I still need to finish working on a larger fix before I can push the update to wordpress.org. 

Should be done in the next day or two if all goes according to plan.

**Comment by tosokuzma** [comment]
Wow thanks so much!

**Comment by dsifford** [comment]
@tosokuzma 

The update is still not ready for wordpress.org because there are lots of pretty drastic changes to how custom citation styles are handled that I need to document and test more thouroughly test, but you can download a copy of a beta version from here: https://github.com/dsifford/academic-bloggers-toolkit/releases/tag/v4.13.0-beta

This should hopefully resolve your issue.
