### ISSUE TITLE
Incorrect error message stops plugin from working

### ISSUE THREAD

**Issue by gconyers** [dsifford/academic-bloggers-toolkit#409]
**ABT Version:** 4.13.0-beta.1

**PHP Version:** 5.5.38
--

**Make Plus:**

**Plugin List:**
- ABT
- Contact Form 7
-Disqus
- Edit Flow
- Exec- PHP
- Google Analytics for WP
- Jetpack
- Make Plus
- Participant's Database
- Popup Ally
- Re-add text underline and justify
- Sensei
- WooCommerce

**Browser:** Google Chrome (Version: 63.0.3239.108)

**The plugin to accept the date since it's in the format it asks for.**

**The plugin didn't accept the date format.
<img width="449" alt="screenshot" src="https://user-images.githubusercontent.com/4678920/34684819-604fbbc4-f474-11e7-8db6-ebaf51244c53.png">
**

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment]
Sorry about that. The fix for this has not been released to wordpress.org because I haven't had time to test it thoroughly, but you can download a beta version from here if you're okay with that: https://github.com/dsifford/academic-bloggers-toolkit/releases/tag/v4.13.0-beta.1

**Comment by gconyers** [comment]
​No worries. I told my writers to cite things manually for now. Though,
I'll give the beta version a try as well to see if it doesn't make their
lives easier.

- G. ​
​​
​​



<http://insanitek.net/>

Grace Conyers Founder and head geek
Email me: gconyers@insanitek.net
Call me: 317.759.1284

[image: Twitter] <https://twitter.com/Insanitek> [image: Facebook]
<https://facebook.com/InsanitekRD> [image: LinkedIn]
<https://linkedin.com/company-beta/3315307/> [image: Google+]
<https://plus.google.com/+InsanitekResearchandDevelopment> [image:
Instagram] <https://instagram.com/insanitek/> [image: Pinterest]
<https://pinterest.com/Insanitek/>

<http://insanitek.net/>insanitek.net

To get me on your terms, make an appointment:
*https://insanitek.acuityscheduling.com/*
<https://insanitek.acuityscheduling.com/>

**Comment by mjluser1** [comment]
I also am having this problem and am having to use a work-around.  I import my .ris database, so I export a new reference from JabRef to the clipboard and then post it into my .ris database that is open in Notepad++.  Then I have the new references available for new posts and pages.  However, I cannot add them to existing posts and pages without deleting all references and reimporting.  I write academically and use many references.  **Please** as soon as possible test your beta fix and make it available.  You have done a **fantastic** job creating this plugin and it **much** appreciated.  Thanks!.

**Comment by dsifford** [comment]
@mjluser1 Sorry to hear you're running into issues.

Can you clarify what exactly is causing trouble for you? Is it the date fields as described in the issue description, or is it importing RIS from jabref?

If the issue has to do with the imported file, can you attach an example file that I can try?

Finally, if you could provide a set of step-by-step instructions for how to trigger the issue you're running into, that would be very helpful.

**Comment by mjluser1** [comment]
It is the same date issue.  Thanks to a post elsewhere about how to clean
up the JabRef exported lines, import is working great!  But when trying to
add a new reference of any type any where, I get the same error message
shown in the other person's post four days ago. As soon as I can work in a
sandbox instead of on my production system, I will download the beta you
wrote to test if it solves the problem in 4.9.1 WP.

Thanks for the quick response, and again, what you are doing is great! I
tried your plugin first for my new blog but then couldn't import so
explored probably all the other plugins for doing references and bibtex.

Yours is far above what they can do in results.  I only have two pages to
convert over from another plugin and I already have a draft page as a list
for PhysicsSpot.com as a whole.  I am pasting entries from my huge JabRef
database to create a static-list database for the entire site. That works
perfectly in your plugin.

I've been a user-experience consultant for 25 plus years since getting my
Ph.D.  The physics work is to make physics easier to learn and use.

If you would like feedback or I can help you in ways like that, I will be
glad to.

Martha

------------
How many things, too, are looked upon as quite impossible until they have
actually been effected? Pliny the Elder, Book VII, sec. 6

**Comment by mjluser1** [comment]
Also, I just discovered JabRef exports the Editor field to .ris identified as A2. Then your plugin ABT identifies it (appropriately) as a second author.  So I am going to have to hand-craft entries with editors either before or after import.  How can I get a list of field ids ABT uses? Then I can check in Notepad++ to change field names as necessary.  Thanks!

**Comment by dsifford** [comment]
Yikes! I don't want you or other users to have to go through that to get jabref to cooperate with ABT. I'll take a look at [jabref's RIS implementation](https://github.com/JabRef/jabref/blob/723af6dddfb4339e5f5fec3bb38869344201c287/src/main/java/org/jabref/logic/importer/fileformat/RisImporter.java) and see if I can reasonably align mine with theirs (or, if theirs is too non-standard, I'll see if I can at the very least catch it in those scenarios).

The file parsing is done in a separate project of mine. The list of mapped fields for RIS can be found [here](https://github.com/dsifford/astrocite/blob/master/packages/astrocite-ris/src/constants.ts).

Also, I'll work on adding support for blank lines so you won't have to manipulate the JabRef export in notepad prior to importing.

**Comment by dsifford** [comment]
Of note: I currently skip A2 fields because they are non-standard. So it would be trivial to add that one in.

**Comment by dsifford** [comment]
@mjluser1 I just downloaded jabref and tried importing a bibtex entry that I created and it seemed to work fine. Have you tried importing bibtex or have you just tried RIS?

**Comment by dsifford** [comment]
Fixed the broken RIS importer here: https://github.com/dsifford/astrocite/releases/tag/v0.10.0

You should be able to import jabref RIS files in the next release.

**Comment by dsifford** [comment]
Fixed in `v4.13.0`
