### ISSUE TITLE
Feedback on new update 4.13.0

### ISSUE THREAD

**Issue by mjluser1** [dsifford/academic-bloggers-toolkit#413]
First, Thanks for the new release!  ABT is an extremely useful plugin and your responsiveness to issues is deeply appreciated!  

I just installed 4.13.0 and will list feedback below as I work through using it. As a user-interaction consultant for 25+ years, I am consolidating my comments as a single feedback report rather than scattering them across multiple github submissions.  At this point, they all apply to a single field. 

Installation wiped out my default APA citation style and reverted back to the plugin's default AMA.  The X at the right of the field does not indicate to the user that the field has a dropdown for style selection. There is no indication that typing in the first few letters of a style's full name will populate the dropdown with all variations of that style.  The field does not recognize that standard abbreviated names, such as APA. Thus I had to discover by experimentation how to reclaim APA as my default style.

**Comment by dsifford** [comment]
Hi there. Great feedback!

> Installation wiped out my default APA citation style and reverted back to the plugin's default AMA

Yeah, there was a known risk of that happening on this one because I was forced to adjust the shape of the data stored after changing how the custom style workflow works. Sorry about that. Hopefully the shape now can remain.

> The X at the right of the field does not indicate to the user that the field has a dropdown for style selection.

The "x" is a browser-specific feature. Chrome, for example, automatically adds them to any input field with the type `search`. 

> There is no indication that typing in the first few letters of a style's full name will populate the dropdown with all variations of that style.

This is one of the biggest struggles I'm currently facing with the reference list. There is simply not enough space available to adequately add labels. I experimented with a few other ways to label the field and they all ended up looking and feeling clunky.

> The field does not recognize that standard abbreviated names, such as APA. Thus I had to discover by experimentation how to reclaim APA as my default style.

I thought I might receive some pushback about this. There are technical reasons that had to be considered when adding the search feature for this.

As an aside, it's important to note that there are currently around 8,500 individual entries in the predefined citation type list. Also important to note that each keypress triggers a re-index of the matches (in other words, all 8500 styles need to be scanned to see which match the search pattern, and then matches are added to a new "matching" list to be displayed to the user).

There were two options:

1. Add a robust "fuzzy search" library to help efficiently process searches using fuzzy matching on both the field label and ID which would lead to the most accurate results at a tradeoff of adding a non-trivial amount of bloat to the overall size of the files needed to be loaded on page load.

2. Match using a very naive, but efficient search algorithm that only counts a match if the label of the style matches exactly the search pattern (normalized to lowercase and with trimmed whitespace). Tradeoff here was a less accurate search experience, but came with a reasonable speed and didn't require adding an external dependency.

Needless to say, I decided to go with option 2. However, option 1 is still not out of the question. 

Thanks again for the feedback. Consider this an open invitation to chime back with any other suggestions you might have.

**Comment by mjluser1** [comment]
Great responses.  Thanks!  

All of the issues I raised could be easily dealt with in a User Guide that comes with the plugin (versus have to be techie enough to deal with GitHub).   I thought that might happen so wrote my feedback to serve as that if tweaked a little. 

I just tried the importing.  Grade A+ on direct importing of JabRef untouched .ris files.  Thanks!  However, the imported list (cited and uncited) is disappearing when I save the post and preview it and then go back to the draft in its original tab.  It does not seem to matter whether the list is pinned or not. (I do have to close the list to see the Save Draft button.)  Also, the one reference I had inserted does not show in the reference list on the preview.  

You asked if I had tried any other export filters, and I had not.  The only BibTex in my list exports to .xml, and ABT does not handle it.  I also tried .txt (for Endnotes), and again it failed. So apparently .ris is my only option.

**Comment by mjluser1** [comment]
I cannot separate the two issues: (a) getting the property bug, and (b) the list of references disappearing from the draft page.  Here is the steps for the references disappearing. When that is solved I probably can give you the steps to replicate the property bug.  I thought if I cleared the cache and closed chrome the problem might disappear but it did not. 
1. completely left wordpress
2. came back to site and opened dashboard
3. Reference list was empty
4. Imported reference list
5. Opened uncited list
6. Got ABT properties error dialog box
7. closed WP draft post tab
8. Reopened tab because forgot to clear cache
9. Cleared cache of all pages
10. Closed tab
11. Closed chrome
12. Reopened chrome
13. went to site
14. opened dashboard
15. when to all post and opened post I had been working on
16. No list of references in ABT
17. imported .ris file
18. saved draft pages
19. List of references disappeared
repeated import .ris and save draft command and the problem replicated consistently

**Comment by dsifford** [comment]
@mjluser1 Superb feedback and details. Really helpful. Thanks

> All of the issues I raised could be easily dealt with in a User Guide that comes with the plugin (versus have to be techie enough to deal with GitHub). I thought that might happen so wrote my feedback to serve as that if tweaked a little.

Sorry for the scant documentation. I'll admit that it's my least-favorite thing to do and I have a tendency to neglect it.

With that said, if there is anything that you'd like to be added, changed, feel free to click the "edit" button on the wiki page and make any changes you feel are helpful/necessary. (I just enabled the option to allow non-collaborators to contribute to the wiki -- didn't realize I had the restriction set).

> You asked if I had tried any other export filters, and I had not. The only BibTex in my list exports to .xml, and ABT does not handle it. I also tried .txt (for Endnotes), and again it failed. So apparently .ris is my only option.

Sorry for the miscommunication. To clarify, only bibtex and RIS are supported right now.

> For inserting entries, how about one click to select, two clicks to open detail box, and (suggestion) three clicks to insert into document. It is a pain to have to scroll back up and find the Insert Reference button.

I'm not sure 3 clicks will be ideal, particularly on devices with trackpads. But I do hear your concerns that it's annoying to have to navigate the mouse all the way to the top each time. (I'll open a separate issue for this).

> Is there a list of the bibtex types ABT recognizes? I just looked at an "Electronic" entry and it missed all the fields but author and title. It took author as contributor, and title as a generic note.

There's no user-facing list available for reference, but if you're interested, you can see all the types that I have registered here: https://github.com/dsifford/astrocite/blob/master/packages/astrocite-bibtex/src/constants.ts#L153-L172

I very well could have missed some or made an error, so let me know if that's the case.

> Sorry to be id'ing so many issues, but I think you want to know. I often trigger this error message, and it seems to be when I have changed the second author into the editor.

No apology necessary! I appreciate you letting me know. Otherwise I'd have no idea these issues are happening!

This particular issue you mentioned is one I've been chasing for a while. Thanks for the details. I'll see if I can trigger it. (opening a separate issue for this)



Thanks for the reproduction steps. I'll give it a shot soon and see if I can trigger it.

**Comment by mjluser1** [comment]
I checked the list for reference types and only found two in JabRef 2.10 that you do not have: (a) online and (b) other. However, it is definite that ABT took only two fields from Electronic without carrying their field names with them.  I could not find a way to edit the entry, such as adding the data field that ABT missed.  I need ABT very much (as I said earlier, no other citation/reference plugin comes close).  I could explore if converting Electronic enties to another type would work.

**Comment by dsifford** [comment]
@mjluser1 Can you open another issue citing your concerns with bibtex importing (and ideally include an example file that I could try)?

Thanks

**Comment by mjluser1** [comment]
I think this is a JabRef export filter problem, not an ABT problem.  There is no option to export Bibtex listed in the set of filters other than BibTexML that exports .xml file.  I tried a .bib file just in case that is what you meant, but it was not recognized as a legal input file type.

**Comment by dsifford** [comment]
The fields for bibtex can be found here: https://github.com/dsifford/astrocite/blob/master/packages/astrocite-bibtex/src/constants.ts

and here: https://github.com/dsifford/astrocite/blob/master/packages/astrocite-bibtex/src/parser.ts
