### ISSUE TITLE
Cannot read property "properties" of undefined error

### ISSUE THREAD

**Issue by dsifford** [dsifford/academic-bloggers-toolkit#415]
Related: https://github.com/dsifford/academic-bloggers-toolkit/issues/413#issuecomment-357780221

> @mjluser1 "I often trigger this error message, and it seems to be when I have changed the second author into the editor."

**Comment by mjluser1** [comment]
Aaarrgh!  I cannot get rid of the error message so that I have ABT working again.  What is the process for getting ABT to reboot and start from scratch? Closing WP and even closing Chrome did not work.

**Comment by dsifford** [comment]
Pushing the fix this error right now.

**Comment by mjluser1** [comment]
Updated it.  I will let you know what happens.  Thanks!

**Comment by dsifford** [comment]
To start from scratch on a post, open the menu and click "Delete all references".

The fix that I'm pushing out targets only the references not being saved on save and reload. (It'll be version 4.13.2 --- still not published yet)

**Comment by dsifford** [comment]
Oops --- disregard my comments @mjluser1. I was talking about issue #416, not this one. Haven't ever been able to reproduce this one yet.

**Comment by mjluser1** [comment]
It kept my default as APA 6th!  Thanks!  (OK, I had wondered---)

Because I am moving text over from Latex, I am fortunate that deleting all references does not lose the \cite info in my document.  However, anyone without that extra info would lose track of the places and entries they had referenced if all the ABT citations are removed. Can you warn them of that or maybe figure a way to not surprisingly lose their work?

**Comment by dsifford** [comment]
Having the reference list just re-update itself is the function that "Refresh reference list" does.

That's generally the one you'd want to press. Delete all is for when all else fails.

In any case, if you've deleted references and realize it was in error, just exit out of the post without saving it and return and they'll show up again.

**Comment by mjluser1** [comment]
Not sure where to leave this comment --- I have updated to .2, but it was doing the same thing in .1.  It kept my desired citation style (APA 6th) and reference style (link + source) in the plugin settings.  But now I get a superscript number instead of name, year as the citation in the text.  AFAIK, I did not change anything to cause this.

**Comment by dsifford** [comment]
Try changing the citation style to something else and then immediately changing it back to APA in the post you're working on.

**Comment by mjluser1** [comment]
Went to plugin settings and changed to IEEE access.  Came back to page and changed to APA 6th.  Then noticed my cite/uncite list had disappeared.  Reimported the database. Inserted a ref. Changed its 2nd author to editor in the list. It changed correctly in the cite.  On different entry changed 2nd author to editor. Then inserted it.  All citations and reference list showing correctly.  Saved draft page.  Ref list still there. Did preview and everything was Ok on previewed page. Went back to draft page and save again. List is still fine.  <deep breath>  Thanks!

**Comment by mjluser1** [comment]
Just got the properties error again and nothing will fix it but deleting all references!  Then, of course, every reference in the document disappears. I can rebuild it because I will not delete my \cite info until a post is published or this issue has been resolved for drafts.  However, users who do not have that backup latex info **will lose all information** about which references had been inserted and where.

**Comment by mjluser1** [comment]
**New Info:**  The Delete all references did **not** delete all references.  I thought it had because they all citations disappeared from the document text I could see, and I could now insert a new ref without getting the error msg.  (Notice that the list of references did not disappear when I deleted all references.) But when I scrolled to the beginning of the document, I discovered that deleting the references had moved all the insertions before the first letter of the document text.  Then I scrolled down to the bottom, and all the references are still listed as they should be.  So I did a Save Draft and the a Preview, and the previewed page showed both the insertions at the beginning and their references in the list at the end.

**Comment by mjluser1** [comment]
This is the same as #error #402 that has been marked as invalid.  However, I do not use SiteGround and I cannot find anything on or through my cPanel that would clear my static cache.  So at least for me this is still a valid issue.

**Comment by dsifford** [comment]
Unfortunately, the issue you're speaking of is too abstract for me to be able to comprehend. It sounds like you're doing a lot of copy/pasting text with references in the editor which is the quickest possible way to certain disaster.

My advice would be to avoid doing any copy/paste operations in the editor.

Also, just to make it clear, the plugin has not ability to comprehend bibtex inside the editor.

**Comment by mjluser1** [comment]
I cut-and-pasted references only after the problem started occurring as part of an attempt to fix it.  So pasting should not be involved in any way as a trigger. 

For anyone reading this comment, the workaround for the property error (this thread and #402) is to put a id marker where you want references and then insert from ABT as the last step before publishing.  It has been working fine since I started doing that. You can permanently hide your reference ids with Hide This plugin so that they remain within the file as backup info.

Not using BibTex within the editor, so no problem there. And so far have managed to be ok with special characters.

**Comment by dsifford** [comment]
@mjluser1 Can you clarify what you mean here:

> put an identifier where you want a reference and then insert there from ABT as the last step before publishing. It has been working fine since I started doing that. You can permanently hide your reference ids with Hide This plugin so that they remain within the file as backup info.

Not sure I understand.

**Comment by mjluser1** [comment]
I cannot consistently replicate the error where ABT locks up on the property error. I have only found destructive ways out of that error.  It shows up fairly often, which makes trusting ABT with all my citation placement info unacceptable.  As you have responded (#402), it appears to be a server cache error.  For example, ABT inserted info keeps showing up on reload even after it supposedly has been completely removed from the post draft. 

Therefore when I want to insert a reference while writing I write [hide]\cite[optional page#]{JabRef_id_string}[/hide] at the reference location.  Because of the Hide This plugin, this info displays only on the draft page and does not ever go into the HTML (if I am remembering correctly).  Then when I have the draft completely written, I make one pass though inserting ABT citations with the results
[(ABTinfo), p. id] [hide]...[/unhide].  I proof the reference list and then publish the post or page. 

That gives me the beautiful Reference List and citations from ABT, and it guarantees that ABT will never again cause me to lose my info about every inserted citation in a document. Also, when I convert the blog pages into a book, all the latex references are already complete and the extraneous ABT info can be deleted easily.

**Comment by dsifford** [comment]
Sorry for the trouble.

I still have never been able to reproduce these types of errors. If you can either provide me steps that you take to trigger each individual one consistently, or send a link to a screen recording of you triggering the errors, that'd be great.

Of note: These errors are the likely cause of me preparing to transfer over to gutenberg. Once gutenberg lands in WordPress stable, the editor that you are now using will be gone and replaced. So my hope is that these sorts of issues will not occur after that happens.

Thanks for your patience.

**Comment by dsifford** [comment]
Closing this issue thread for now since the issue is still too illusive for me to make any action on.

Feel free to reopen if any further details emerge.

**Comment by nerdyandawesome** [comment]
Hi, I am having this "properties" bug and I can replicate it. I couldn't find another thread with a solution. That's why I'm reopening this. Sorry if this is a duplicate and appreciate a pointer to the resolved thread.

I have the latest version of WordPress 5.1.1 running Foodie Pro Theme theme. Using Genesis 2.9.1.

I have installed Classic Editor to use the classic version. But before I did this, I used the new editor on a few posts.

It appears whenever I copy and paste paragraphs from an old post to a new post, this bug appears. 

Nothing can get this bug to go away, even when I try to look at the html and look for suspicious style elements.

Once this bug appears, the only thing I can do is to create a new post and hand-type the paragraph or "copy text only" all over again. 

Does this help figure out the issue?

**Comment by dsifford** [comment]
> It appears whenever I copy and paste paragraphs from an old post to a new post, this bug appears.

If those paragraph contain references, that's a no-go and will 100% cause problems.

Behind the scenes the editor keeps track of metadata in the html of those references and if you introduce new references without the plugin being explicitly aware of them, it'll cause a cascading sequence of catastrophic errors.

So, in other words, don't do that.

**Comment by nerdyandawesome** [comment]
That makes sense. Thanks a lot for the info!
