### ISSUE TITLE
Database questions

### ISSUE THREAD

**Issue by mjluser1** [dsifford/academic-bloggers-toolkit#417]
As I mentioned elsewhere, I am building a JabRef database specific to my new blog (PhysicsSpot.com) from scratch by pasting individual entries over from a database with 1100+ entries. I add the entries to PS database as I find the citation in the Latex document I am converting to a post in the PS blog. Thus the size of the imported database for page x is not the same size as the imported database for page Y.   There is also page Z that has a static list of everything in the database (i.e., everything that has been cited across all PS posts).

How do these databases relate to each other?  If I go back to page x and want to add a reference I had added later on page y, do I have to add it as an individual entry on page x.  What do I need to know about how the different post databases relate to each other?  Thanks.

**Comment by dsifford** [comment]
Not sure if I fully understand what three databases you're referring to are. I'm assuming you're talking about data structures within JabRef so forgive me if I misread.

To speak directly about how data is saved using ABT:

The only data that is globally available to all posts is the data that you set on the options page (e.g., bibliography style, default citation style, etc). 

The references and citations are saved as post metadata to each individual post. In other words, posts that contain references are only aware of the references that they contain. They cannot "see" the references that other posts contain, nor can they use or reference and data that is contained in any other post (It might help to think of each post as an individual silo of information). The reason for this is deliberate. 

I've had a few individuals ask if I could implement a feature that allows them to _manage_ references within WordPress. In other words, store references in some globally available location that you can then look up in posts later on down the road. Although I understand the appeal, that is not a feature that I plan to implement because I firmly believe that references should not be _managed_ on WordPress. Instead, they should be managed using a robust reference management application (e.g., Zotero, EndNote, etc) and then _displayed_ on WordPress. That's one of my core philosophies.

**Comment by mjluser1** [comment]
I thought that was the way ABT worked, but I wanted to be sure.  I agree that WP is not the place to manage references.  It would help if adding an uncited to one page added it to all the others, especially because of the difficulty in browsing the uncited list as it gets lengthy.  If I added Einstein in Stachel to one page and then need it on another, I have to figure out how to reimport the newer database including that ref for the post where I need to add it or else manually add it (which leaves me very open to typing errors).  It could be a simple add to post (select from list) from the metadata (cited and uncited) in another post.  Then the info cited in both posts would have to be identical.  

Somewhere I saw a mention to refreshing a database, but I have not located an explanation of that.  Perhaps that solves the problem and I do not yet know how to do it.

**Comment by dsifford** [comment]
> It would help if adding an uncited to one page added it to all the others, especially because of the difficulty in browsing the uncited list as it gets lengthy.

I understand the appeal here for sure, but there's technical reasons why this just isn't feasible.

> Somewhere I saw a mention to refreshing a database, but I have not located an explanation of that. Perhaps that solves the problem and I do not yet know how to do it.

Might not be documented. There's a button with the label "Refresh reference list" that, when clicked, scans through the entire document to find locations where there are citations that are out of sync with the processor and then either prunes them out or labels them "broken" so that the states between the document and the processor realign. 

This is a non-destructive fix whereas the "Delete all references" button is a destructive fix. "Refresh" works sometimes, "delete" works always.

**Comment by mjluser1** [comment]
Is there a warning message before pruning?  Where does the "broken" label show up?

**Comment by dsifford** [comment]
No warning message before pruning because it doesn't prune them from the editor when doing a "refresh"... Just behind the scenes. 

When it meets citations that it is not aware of (aka, "broken" citations, the metadata is stripped from the citation node and the text "BROKEN" (bold and in red) is prepended to the existing citation. So it generally becomes obvious when there are extra citations in the editor. This is the more rare case.

Usually, when users run into issues where "refresh" helps is when the processor behind the scenes thinks there are _more_ citations than actually exist (so, a circumstance where the user deleted a citation without the processor being aware of it). In that circumstance, the pruning happens exclusively behind the scenes and the user won't notice any change.
