### ISSUE TITLE
JabRef to ABT plugin

### ISSUE THREAD

**Issue by mjluser1** [dsifford/academic-bloggers-toolkit#419]
ABT imported the .ris file exported by JabRef without displaying any error messages.  However, as I explore inserting references from my uncited list I am beginning to find issues.

For example, this is the picture of a BibTex item.
![image](https://user-images.githubusercontent.com/34763693/35019182-89d0aa6e-faf3-11e7-86c0-5db402786947.png)

This is how the item was exported into the .ris file. AFAIK, it imported into ABT correctly.
![image](https://user-images.githubusercontent.com/34763693/35019227-b8e2d728-faf3-11e7-93b0-0e716b5ea23b.png)

However, this is the picture of the reference in the draft page on my blog.
![image](https://user-images.githubusercontent.com/34763693/35021681-e7aa45a8-faff-11e7-8911-7518ece315d3.png)

This is the picture of the published reference.
![image](https://user-images.githubusercontent.com/34763693/35019305-36802ea6-faf4-11e7-887e-9176d1425c69.png)

Issue:  ABT put the p. for page in front of the Doc. number. That is logical, but I need a place to put the Doc. number so it shows up correctly in the reference.

Also, somehow JabRef is including an EP (End Page?) field that is repeated after the range by ABT.  The reference then shows 1st page - last page - last page

**Comment by mjluser1** [comment]
I edited the cited list and move the document number to the chapter field, but it does not print for the InCollection reference.  The page numbers did print correctly after I took out the document information.

**Comment by dsifford** [comment]
Great description and explanation of the issue. 

This issue is going to be specific to JabRef (cc: @lenhard). The export format is not correct. SP must only be a single integer, not a range of integers or any other information. Additionally, EP must also be only an integer.

For doc number info does not go in the page field. Instead, it should go in either `AN`, `C7`, or `M1` (depending on the type of number it's describing).

Closing this issue since this is not something that I can fix. Although I CC'ed @lenhard, you might want to also open this in JabRef's repo.

----

To answer you question about the incollection number: I assume you are citing a manuscript? That format is currently not supported by ABT. The `book` or `chapter` type will not produce what you're looking for.

**Comment by lenhard** [comment]
@dsifford Thanks for the notification. I think it would be best if we list or reference all RIS field errors in the issue you already opened: https://github.com/JabRef/jabref/issues/3634
