### ISSUE TITLE
Numbered individual documents by same author within a book with volume number

### ISSUE THREAD

**Issue by mjluser1** [dsifford/academic-bloggers-toolkit#420]
Applicable pictures were pasted into #419.  You wrote, 

> To answer you question about the incollection number: I assume you are citing a manuscript? That format is currently not supported by ABT. The book or chapter type will not produce what you're looking for.

The numbered documents are in _The Collected Papers of Albert Einstein_.  Each book (volume) is a collection of numbered documents, and I am citing the individual documents.  They import fine except for the closed issue of page numbers.  

However, I still need to find a way to include the document number if at all possible. As the volume number of the book is in the title, I took it out of its own field. I will try using that field for Doc and see what happens.

**Comment by dsifford** [comment]
I don't think this is going to be something that I can really add support for since this is such an isolated and unique case. Adding support for something like this creates an extra layer of complexity for the entire codebase and it's not really something I'm prepared to add in at this time.

I'm not sure there currently exists any citation type for the collection you are describing. 

My suggestion would be to just find whatever citation type matches the closest and do your best. Sorry about that.
