### ISSUE TITLE
Plugin could not be activated

### ISSUE THREAD

**Issue by yos3prens** [dsifford/academic-bloggers-toolkit#423]
**ABT Version:** 4.13.2

**PHP Version:** 5.6

**Theme:** Twenty Fifteen

**Plugin List:**
- Akismet Anti-Spam
- FooGallery
- Google XML Sitemaps
- Jetpack by WordPress.com
- LearnPress
- LearnPress - Course Review
- LearnPress - Fill In Blank Question
- LearnPress Courses Wishlist
- LearnPress Offline Payment
- Molongui Authorship
- Olevmedia Shortcodes
- PDF Viewer
- Per page head
- Popup Maker
- Super Socializer
- Table of Contents Plus

**Browser:** Google Chrome (Version: 63.0.3239.132)

**Expected behavior:** I can install Academic Blogger's Toolkit in my website: http://people.usd.ac.id/~ydkristanto/

**Actual behavior:** Academic Blogger's Toolkit could not be activated because it triggered a fatal error

**Console messages:**
```js
// Parse error: syntax error, unexpected '[' in /home/***/public_html/wp-content/plugins/academic-bloggers-toolkit/academic-bloggers-toolkit.php on line 69

```

**Comment by dsifford** [comment]
@yos3prens It appears that you're using a php version < 5.6. 

In the release notes for the last release, I stated that I am no longer supporting old, outdated PHP versions (for now, versions < 5.6, but in the near future versions < 7.0) because they pose a security risk on the site operating them, they're slower (by a factor of 3), and they are difficult to maintain support for.

So, in short, your options would be one of the following:

-  Contact your hosting provider and have them update your php version (Ideally, to version 7.2, but at least to php 5.6).
- Roll back to an earlier version of this plugin.

**Comment by yos3prens** [comment]
Thank you @dsifford for your assistance. Where can I get the early version of the plugin?

**Comment by dsifford** [comment]
Older versions of the plugin can either be downloaded from the [releases page](https://github.com/dsifford/academic-bloggers-toolkit/releases) of this github repository, or from [this page on wordpress.org](https://wordpress.org/plugins/academic-bloggers-toolkit/advanced).

Keep in mind though that older versions might have bugs and might stop working eventually since they aren't supported any longer.

I highly recommend updating your PHP version if you can. More details about how and why can be found here: https://github.com/WordPress/servehappy

(wordpress is going to start enforcing this soon as well so you'll eventually _have_ to update).
