### ISSUE TITLE
Bibliography after list gets pulled into the list

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#432]
This is not an issue with ABT I don't think, more of a Wordpress thing that impacts ABT.

When a page has a list at the end, followed by the bibliography, Wordpress pulls the bibliography into the list, placing the closing tags `</li> </ul>` after the bibliography.  The bibliography gets indented immediately under the list; not a good look.

I've tried putting a `<span> </span>` between them; it disappears.  I've tried wrapping the list in a `<div>`, but WP just moves the `</div>` after the bibliography as well.

Any ideas how to trick Wordpress into dropping this behavior?  I'd also like to avoid adding extra space between them.

**Comment by dsifford** [comment]
Not sure.. I'll have to check into it.

Of note: This won't be an issue once Gutenberg lands in WordPress Core (and once I actually get around to implementing the plugin for Gutenberg, which will likely be a bit later than the launch date).

If it is something that I can fix and is easily fixable, I'll add in a fix. Otherwise I might just hold off and prioritize Gutenberg support.

**Comment by dsifford** [comment]
Done.
