### ISSUE TITLE
citation manager down?  

### ISSUE THREAD

**Issue by joshdf** [dsifford/academic-bloggers-toolkit#497]
Which web browser are you using (including version)
- Safari

The reference/citation plugin has started to refuse to insert new citations, when using either PMID or DOI.  This seems to be occuring across multiple different articles (not just a single article).  When I try to create a new reference by inserting the PMID or DOI number, I get the following error message: 

An unexpected error occurred TypeError: undefined is not an object (evaluating 'this.registry.citationreg.citationById[i[0]].properties') Please report this error, including the steps taken to trigger it, here: https://github.com/dsifford/academic-bloggers-toolkit/issues

thanks, josh

**Comment by dsifford** [comment]
Not totally sure and unfortunately don't have the time right this moment to check on it but it sounds like something that happens when citation metadata becomes corrupted.

I'm not going to focus all that much on this particular issue because once I have the time to spare I plan on migrating the plugin over to the new gutenberg editor.

My suggestions would be for now to just see if it still occurs on brand new posts and if it does, use a better browser (chrome or firefox).

**Comment by joshdf** [comment]
Eventually figured out what happened.   I cut & pasted a block of text that *included* a citation within it.  That somehow corrupted the citation which had been cut/pasted, which seems to have messed up the numbering system for all the citations and prevented me from entering any subsequent citations.

After deleting the corrupted citation everything seems to be working now.

So life is good, will avoid cut/paste with citation in future.

thanks much, cheers, josh

**Comment by joshdf** [comment]
Glad it worked!
