### ISSUE TITLE
Headings by Year for "APA CV"

### ISSUE THREAD

**Issue by sgoggins** [dsifford/academic-bloggers-toolkit#51]
I think for websites most academics want to be able to have headings by year. 

Also, "APA CV" is kind of a guess.  One that worked, but just a guess. So, having a way to sort by year or alphabetically is generally useful regardless of the citation style, I think.

**Comment by dsifford** [comment]
@sgoggins Agreed. 

It's totally possible, but I still haven't quite figured out how to best go about implementing it (things become tricky being that, at baseline, users are able to click and drag references around the reference list).

I'm just about to get started on an enormous update to the citation processor; the goal in mind for the update is to 1. Allow different sort-by options (either determined by the user or by the citation style) 2. Insert the correct inline citation format, rather than just a bracketed set of numbers, and 3. Be (by and large) much more efficient.

Unfortunately, I don't have the slightest idea of when I'll have that finished.

Thanks for the feedback. Keep 'em coming! 👍

**Comment by dsifford** [comment]
@sgoggins Automatic sorting based on citation type will be added in the next update I'll be pushing out shortly. 👍
