### ISSUE TITLE
Pagination of Long Bibliographies

### ISSUE THREAD

**Issue by sgoggins** [dsifford/academic-bloggers-toolkit#52]
Not sure how much effort this would involve. Or even how important it would be if there are year breakdowns ... One of the things I like about the biblio plugin on drupal is it does paginate and let you sort by year ... Here's my current publish on a test site in your tool ..

http://datascience.goggins.com/7-2/

BTW, love this plugin MUCH more than ZOTPAD ... I like how its built to be movable and not dependent on wordpress.  Really good, durable software engineering decisions. :)

**Comment by dsifford** [comment]
I greatly appreciate the kind words! 😄 

I like the idea, but I think in order to do it justice this would have to be made into a feature separate from regular blog post bibliographies. 

I'll tag this as `future` for now and come back to it once the dust settles from the other open issues. 

For the time being, I _believe_ Biblio has a WordPress plugin as well, don't they? Maybe that would be able to hold you over until I can devote some time to this?

**Comment by dsifford** [comment]
Closing in favor of #123 (this would be a feature of that) -- feel free to chime in there.
