### ISSUE TITLE
Reference List option keeps on buffering

### ISSUE THREAD

**Issue by msgarde** [dsifford/academic-bloggers-toolkit#533]
Hi Derek,

I have the current version of ABT (4.13.3) which does not seem compatible with the latest version of WordPress (5.0.2). In the newer version of WP, the Reference List option keeps on buffering in the editor (please refer to the screenshot). So, I'm unable to see previously added references as well as to add new ones.
![screenshot 4](https://user-images.githubusercontent.com/46309913/50581906-0bec0580-0e84-11e9-8897-0b374be267c1.png)

I wanted to ask if there is any way to fix this issue. Otherwise, will you be updating the ABT version in the near future?

Thanks.

**Comment by dsifford** [comment]
You are correct. The current plugin version is not compatible with the new editor in WordPress 5. I’m working on an update right now actually which should be done in about a week or two. The update will be backwards compatible with all of your previous posts and allow you to convert from “classic” to “block” format in the new editor in one click. 

You’ll need to upgrade your PHP version to at least PHP 7.2 in order to install the update once it is released though.
