### ISSUE TITLE
Citing Patents, Patent Number should be a string

### ISSUE THREAD

**Issue by hartrusion** [dsifford/academic-bloggers-toolkit#554]
**ABT Version:** 5.0.4

**PHP Version:** 7.2.15

**Theme:** Neve v2.3.4

**Plugin List:**
- Academic Blogger's Toolkit
- Classic Editor
- Contact Form 7
- Contact Form 7 Honeypot
- Delete Me
- Disable Google Fonts
- Easy FancyBox
- Enable Media Replace
- Google Captcha (reCAPTCHA) by BestWebSoft
- Mime Types Plus
- Polylang
- Super Socialize

**Browser:** Firefox v66.0.4

**Expected behavior:**
Adding a Patent to the Bibliography List and cite it as:
[1] W. Wolsky, “Deep Boring Apparatus,” US699273, 10-Sep-1900.
Or, in general therms, cite patents like: DE102017005548A

**Actual behavior:**
Patent Numer is implemented as a number only, but they are usually document numbers including letters like "US", "WO" and "A1", "B2" and so on at beginning or end. Bibliography IEEE (with url) list then shows:
[1] W. Wolsky, “Deep Boring Apparatus,” 69927310-Sep-1900.
The whitespace and comma after patent number is also missing on this template, on IEEE standard template the "," and whitespace is working.

The Patent Number is implemented on the form as number, like:
`<input required="" autocomplete="off" data-lpignore="true" type="number" value="NaN">`
So its not possible to add it to the bibliography list.
A workaround using a .ris-File upload with "M1  - DE102017005548A" does the job! But the number can not be edited then in the plugin window aftwerwards.

At last, let me say your plugin is a great thing to work with, everything else works perfect. I absolutetly love it and highly appreciate your work!

**Comment by dsifford** [comment]
Thanks. I'll get this fixed hopefully soon.

**Comment by hartrusion** [comment]
Thanks a lot. I encountered some more things when doing RIS import of patents: The "Date" field gets imported from entry "PY" which is just the year, butyour plugin also allows full YYYY/MM/DD here what makes sense. There is another field just called "Date" C2 which would be more suitable to import as application date. if not available, the "issue date" DA could also be used.
A2 and A3 get also imported as inventors, but they are Issuing Organisation and International Author as far as I could get information about RIS specs. Inventors are all listed with "AU", this works prefect.

**Comment by dsifford** [comment]
Hi there,

Lots to unpack in your message, so forgive me if I miss something...

> The "Date" field gets imported from entry "PY" which is just the year, but your plugin also allows full YYYY/MM/DD here what makes sense.

Are you saying the plugin is not allowing you to add the reference with just the year or?

> There is another field just called "Date" C2 which would be more suitable to import as application date.

This won't work because PubMed and PubMed Central use `C2` for PMIDs and PMCIDs.

> A2 and A3 get also imported as inventors, but they are Issuing Organisation and International Author as far as I could get information about RIS specs.

Since there are far too many possibilities, I just default all parties in the `A*` fields as an author. I'll look into adding Issuer and International Author if you need those. 

If you could, [have a look here](http://docs.citationstyles.org/en/stable/specification.html#name-variables) and let me know which field best describes "international author".

I'll use `authority` for issuing organization.


### Recap

Below is the list of things you're requesting:
1. Make patent number a string, rather than a number.
2. Add in "Issuing Authority" and "International Author" as options in the "Contributors" dropdown.

Let me know if I missed something.

**Comment by dsifford** [comment]
**Update:** `authority` isn't an "author"-type of field. It's a standard string field. So I'll add that in, but just note that it won't be where authors are listed.
