### ISSUE TITLE
How to add a footnote?

### ISSUE THREAD

**Issue by Nakroma** [dsifford/academic-bloggers-toolkit#573]
How do I add a footnote? Theres a "Footnotes" section in the references list, which I want to use. But it's not documented in the wiki nor is there any UI option for it.

**Comment by dsifford** [comment]
There should be an item in the main editor toolbar (near bold/italics/etc) for footnotes.

Sorry about poor docs. Let me know if that helps.

**Comment by dsifford** [comment]
Reopen this issue if you are still having issues. Closing for now since I haven't heard back.

**Comment by Nakroma** [comment]
Yeah sorry, I was away for the weekend, that worked!

Is there a way to change the footnote style (i.e. to numbers)? Right now it's using *​, ​†​ ... etc. and the citation style doesn't seem to affect this, at least for Harvard and IEEE.

**Comment by dsifford** [comment]
Not currently.

The reason for the symbols is so that it is guaranteed to work with all of the available styles. If I added letters or numbers by default, there's a good chance the lettering or numbering would conflict with the user's selected style.

So there will require a decent amount of thought into implementing this, but unfortunately I haven't had time to get around to it just yet.

**Comment by Nakroma** [comment]
Alright, that kinda breaks the use case for me. Thanks for the quick answers anyway :)

**Comment by dsifford** [comment]
What use case might that be?

**Comment by Nakroma** [comment]
Well, just using footnotes and references together, IEEE style.
