### ISSUE TITLE
<i> tag is a problem for accessibility

### ISSUE THREAD

**Issue by askwpgirl** [dsifford/academic-bloggers-toolkit#576]
5.1.0 

N/A

N/A

**Plugin List:**
N/A

**Browser:** N/A

**Expected behavior:**
`<i>` tags for italics do not pass accessibility testing. Should change to `<em>` in all citations.

**Actual behavior:**

**Console messages:**
```js


```

**Comment by dsifford** [comment]
Hi @askwpgirl. 

Thanks for the report. A few things to note:

1. This issue would be something that would need to be resolved in the [citeproc-js](https://github.com/Juris-M/citeproc-js/) project, as that's what generates the tags.
2. I'm not sure that this is an a11y issue in the first place. Per MDN, the `<em>` element "marks text that has stress emphasis", whereas `i` elements "represents a range of text that is set off from the normal text for some reason.". From those definitions, it seems that `<i>` is the correct element to be used here.

Regardless of point 2, since this is not an issue that can be handled here either way, I'm going to close this issue as it's out of scope. If you feel strongly about this, consider opening an issue in the repo I linked above.

Thanks

**Comment by askwpgirl** [comment]
Thanks for the quick reply. Some things marked by accessibility testing tools are confusing. I am curious what the university accessibility review team will say.

To further complicate things, `<i>` tag is now used for icons by FontAwesome, so I am also getting a11y notices about that. Per w3schools, `<i>` should only be used when something more appropriate is not available, e.g.` <em>`. In this case, I think `<em>` would be the correct tag as for citations, since these are italics, not something else.

**Comment by dsifford** [comment]
See this thread: I actually brought this issue up 3 years ago and it was decided against.
