### ISSUE TITLE
Missing Insert Tools?

### ISSUE THREAD

**Issue by DJRob** [dsifford/academic-bloggers-toolkit#599]
**ABT Version: 5.2.2

**PHP Version: 7.3.13

**Theme: WordPress 2020

Activated Plugins: None, aside from ABT

Display ABT Tools to insert references

Tools are absent (see attached). First two show what I have. Last one is what the documentation says I should have. Insert reference is not available. 

**Console messages:**
```js
// Paste messages here
NONE
```
![Capture2](https://user-images.githubusercontent.com/23213456/72193485-5ffec380-33cf-11ea-8225-3f4a6fd65358.PNG)
![Capture3](https://user-images.githubusercontent.com/23213456/72193486-5ffec380-33cf-11ea-9bef-79eb2ced1a1d.PNG)
![Capture](https://user-images.githubusercontent.com/23213456/72193488-5ffec380-33cf-11ea-8e24-1d70f73398bb.PNG)

**Comment by dsifford** [comment]
Hi there!

Sorry about that. I haven't had much time to devote to this project lately and because of that, I've let the documentation become sort of outdated.

The insert reference button will show up in the new editor now only if your cursor is active inside a block that is able to receive an inline citation (so, "text"-type blocks generally).

Let me know if you have any other questions.

**Comment by DJRob** [comment]
Got it. Seems to work okay with what you said. 
Thanks.

**Comment by jugdemon** [comment]
I recently returned to my blog to update some references and I ran into the same issue only your provided solution doesn't seem to work. I am in a paragraph block but no insert button appears. Is there a step I missed?
