### ISSUE TITLE
ABT hiding unrelated Markdown footnotes

### ISSUE THREAD

**Issue by someonehere15** [dsifford/academic-bloggers-toolkit#60]
I use markdown to format the posts, and just noticed something: If I want to add a footnote, which in markdown would be something like [^1], the footnote is being hidden by your plugin. The number is shown inline, but the footnote text at the end of the page is not shown. I disabled your plugin and it worked fine, so I guess there's some conflict. Can you check? I tried it with Jetpack Markdown, not sure if other markdown plugins would do it.

As an additional request, it would be nice if you could make the plugin markdown compatible, so that when the widget inserts references in the text, they don't add a lot of tags and stuff, which especially helps when not using the visual editor. Or the widget can place the references in the form of shortcodes with parameters so that they look cleaner.

**Comment by dsifford** [comment]
@someonehere15 Is the markdown you're using native? Or is a plugin that offers that functionality?

>  it would be nice if you could make the plugin markdown compatible, so that when the widget inserts references in the text, they don't add a lot of tags and stuff

Not possible, unfortunately. Each of the tags that it adds is used by the plugin in the background while you're editing the post and adding references. It's the only way for it to keep track of where things are at.

> Or the widget can place the references in the form of shortcodes with parameters so that they look cleaner.

See the [readme](https://github.com/dsifford/academic-bloggers-toolkit/blob/master/README.md) for details on why this is a very, very dangerous idea.

**Comment by dsifford** [comment]
Also, I suppose I should mention that I'm going to be looking into getting the reference list to work on the text editor soon. See #55

**Comment by someonehere15** [comment]
No problem for the shortcodes. As I said I use jetpack markdown because wp does not natively support markdown anyway. I don't see why it should be a problem since your plugin uses [1]  whereas markdown uses [^1].but as I said the footnote is not shown while your plugin is active, but only when there are no references for ABT to show on the post. It would be a big problem.

**Comment by someonehere15** [comment]
I was also thinking, but didn't get the chance to try it yet. Normally markdown converts the code to html when rendered, so maybe ABT has problems not with markdown directly but with lists at the end or something, which would be a bigger problem. I can't check right now but if I do I will let you know. The markdown thing happens anyway though.

**Comment by dsifford** [comment]
I'll download jetpack later and try it out. It's likely related to how they parse the markdown.

**Comment by dsifford** [comment]
Can't seem to reproduce here on my end.

![image](https://cloud.githubusercontent.com/assets/5240018/15081412/e786072c-1390-11e6-9625-37a841c7f079.png)

![image](https://cloud.githubusercontent.com/assets/5240018/15081423/f2accbe0-1390-11e6-8914-2643822d844a.png)


That said, if you are having issues and you singled the issue down to ABT, then it's likely because I still have some legacy code in it that automatically finds the last ordered list in the post and tags it `abt-smart-bib` on render. (this is so older posts you have can also have tooltips without having to go through and re-insert all the citations again).

**Comment by someonehere15** [comment]
Yes, because you are inserting a reference from ABT too. Try just leaving your plugin active, but without adding references. Just create a new post, insert a footnote, and that's it.

**Comment by dsifford** [comment]
Ah, yeah that'll be because of the legacy code that still exists. I was meaning to take it out within the next couple of releases. If you want you can remove [this function](https://github.com/dsifford/academic-bloggers-toolkit/blob/master/lib/backend.php#L526) from your version which should work until I get it fully depreciated

**Comment by dsifford** [comment]
If that doesn't work let me know and I'll reopen this.
