### ISSUE TITLE
Feature idea: copy and paste between articles

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#75]
One possibly idea came to my mind that might be nice. Have the ability to copy a segment of a post that contains inline citations to the clipboard, then go to another post, and be able to past it there with the inline citations and references being added to the new post.

David

**Comment by dsifford** [comment]
Cool idea.

Just to be clear: You're suggesting a situation where you only copy and paste inline citations to a new post and then the bibliography get's generated on the new post, correct?

Might be possible.

I've been neglecting this plugin for the last couple weeks due to schoolwork and other things occupying most of my time. Once I get caught up, I'll see if this would be something I can add.

One thing that would need to be added prior to this would be a refresh button so that the processor can recreate itself in the event of it going out of sync with the document (That's planned).

A feature I'm planning on getting to first is one that pins the reference list to the window so that it scrolls with the page. I should be able to get to that one soon. Be on the lookout for it! (See #71).

Thanks for the suggestion 👍

**Comment by metallikat36** [comment]
Yes, you got it. Say I copy a paragraph that has some sentences and some inline citations. I paste it to a new post. The new posts adds those references to the references list, and reassigns the correct new numbers to those inline citations. 

Oh man you're still in school? Don't let programming hobbies mess you up. =)

**Comment by metallikat36** [comment]
One more request would be that this copy/paste feature would not require editing a post and then copying from the backend of wordpress. Rather it would be easiest it the url of the post itself could just be viewed like a regular user, and then copy and paste from there. Have no idea if that is possible, but just suggesting it.

**Comment by dsifford** [comment]
Wont be possible after next update because I slimmed down the size of the saved data. All information is computed on the fly from a minimal representation of the data and that won't be something that will be easily copied from one place to another.

**Comment by metallikat36** [comment]
Okay, no problem.
