### ISSUE TITLE
Compatibility problem?

### ISSUE THREAD

**Issue by bamcc** [dsifford/academic-bloggers-toolkit#78]
I'm trying to use this plugin in conjunction with team showcase (http://codecanyon.net/item/team-showcase-wordpress-plugin/4936368) to display publications on individual team member pages, but when PMIDs are entered, pub info is not added to the page. Also doesn't work on pages. Using showcase pro theme on the genesis framework.

**Comment by dsifford** [comment]
@bamcc I won't be able to troubleshoot this since the plugin isn't free.

Can you confirm that you're using the latest version? (3.2.2)

Also, can you attempt to insert a citation again and after it fails can you copy and paste the output from the javascript console? (To do this, press F12 to open dev tools, then click "console", then copy everything there)

What browser are you using? What version of that browser is it?

Thanks.

**Comment by bamcc** [comment]
Thanks for writing back so quickly, @dsifford. Yes, I am using the latest version, using Safari 9.1.1.
Is this it?
[Log] JQMIGRATE: Migrate is installed, version 1.4.1 (load-scripts.php, line 9)
[Warning] Unexpected CSS token: ; (post.php, line 1226)
[Warning] Invalid CSS property declaration at: #11CAA5 (post.php, line 1227)
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (color-pickr.js, line 0)
[Error] ReferenceError: Can't find variable: safari
	global code (content_start_0.js (line 1))
	appendChild
	(anonymous function) (tinymce.min.js:4:785)
	run (tinymce.min.js:4:5927)
	add (tinymce.min.js:4:633)
	init (tinymce.min.js:11:10131)
	(anonymous function) (tinymce.min.js:11:5444)
	(anonymous function) (tinymce.min.js:4:10760)
	n (tinymce.min.js:3:1079)
	p (tinymce.min.js:4:10734)
	(anonymous function) (tinymce.min.js:4:10720)
	i (tinymce.min.js:4:9746)
[Error] ReferenceError: Can't find variable: safari
	global code (iprl5.js (line 25))
	appendChild
	(anonymous function) (tinymce.min.js:4:785)
	run (tinymce.min.js:4:5927)
	add (tinymce.min.js:4:633)
	init (tinymce.min.js:11:10131)
	(anonymous function) (tinymce.min.js:11:5444)
	(anonymous function) (tinymce.min.js:4:10760)
	n (tinymce.min.js:3:1079)
	p (tinymce.min.js:4:10734)
	(anonymous function) (tinymce.min.js:4:10720)
	i (tinymce.min.js:4:9746)
[Error] ReferenceError: Can't find variable: safari
	global code (content_start_0.js (line 1))
	write
	initContentBody (tinymce.min.js:11:10593)
	init (tinymce.min.js:11:10392)
	(anonymous function) (tinymce.min.js:11:5444)
	(anonymous function) (tinymce.min.js:4:10760)
	n (tinymce.min.js:3:1079)
	p (tinymce.min.js:4:10734)
	(anonymous function) (tinymce.min.js:4:10720)
	i (tinymce.min.js:4:9746)
[Error] ReferenceError: Can't find variable: safari
	global code (iprl5.js (line 25))
	close
	initContentBody (tinymce.min.js:11:10615)
	init (tinymce.min.js:11:10392)
	(anonymous function) (tinymce.min.js:11:5444)
	(anonymous function) (tinymce.min.js:4:10760)
	n (tinymce.min.js:3:1079)
	p (tinymce.min.js:4:10734)
	(anonymous function) (tinymce.min.js:4:10720)
	i (tinymce.min.js:4:9746)

**Comment by dsifford** [comment]
@bamcc 

It looks like some other plugin (or theme) that you have installed might be the root of these issues.

**Not loading javascript file (not one of mine)**
`[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (color-pickr.js, line 0)`


**Invalid CSS selectors being used (not one of mine)**
`[Warning] Unexpected CSS token: ; (post.php, line 1226)
[Warning] Invalid CSS property declaration at: #11CAA5 (post.php, line 1227)`

**Errors related to some JS file trying to access a variable that doesn't exist (not one of mine)**
`[Error] ReferenceError: Can't find variable: safari`


One thing I will mention is, you're doing yourself a disservice by using Safari. The best browsing experience (and most feature packed) is Google Chrome, followed closely by Firefox. 

Internet Explorer and Safari lack lots of features and, because of this, will usually generate errors.

What I'd recommend you try is first retrying your current setup using Chrome or Firefox and if that doesn't work, contact the developer of that other plugin you mentioned.

Hope that helps. Feel free to reopen this issue if you're able to figure out additional information.
