### ISSUE TITLE
Having troubles on Edge and Safari browsers

### ISSUE THREAD

**Issue by Vitaliy-1** [dsifford/academic-bloggers-toolkit#95]
Pluging doesn`t work well on Edge, IE or Safari browsers.

Edge and IE - Peer Review boxes are not shown (only "null" text).
Safari - Peer Review boxes are also empty and Bibliography is not displayed correctly (footnote numbers are above reference and journal titles are too _inclined_).
On Firefox and Chrome all works fine.

Or only I have such problems because of specific wordpress theme? (pardon for my English if I make mistakes)

**Comment by Vitaliy-1** [comment]
Hmmm.
Now reference numbers are displayed above the reference text in all browsers. Perhaps after the last update. 
For example, i have this code on my page:
```
<div id="417elqnt">
<div class="csl-entry">
<div class="csl-left-margin">9.</div>
<div class="csl-right-inline">Kelly C, Sohal A, Michael B, et al. Suboptimal management of central nervous system infections in children: a multi-centre retrospective study. <i>BMC Pediatr</i>. 2012;12:145.</div>
<div class="abt-url">[<a href="http://www.ncbi.nlm.nih.gov/pubmed/22958329" target="_blank">PubMed</a>]</div>
</div>
</div>
```
And the number of citation (9) is displayed above the reference.
I`m not a programmer, but i suppose there is something wrong in this :)

**Comment by dsifford** [comment]
@Vitaliy-1 Hi there.

Safari will be completely fixed once Safari 10 gets released. It's in open beta now and should be released relatively soon. Safari 9 is _extremely_ behind the rest of the browsers which is why I assume these issues are happening.

The issues you're reporting with Edge are likely similar to the ones with Safari. Once Edge 14 moves from Insider Preview to stable, the issues will be gone.

I purposefully chose not to support IE browsers, since supporting those browsers will result in a dramatic reduction in features. 

Having said all that, I'll look into making the rendering of bibliographies agnostic to browser version. I agree that people should be able to view a bibliography no matter what browser they choose. I will remain opinionated, however, with my browser choices for physically using the plugin though. 

As for your second issue: That HTML snippet looks like how the bibliographies _used_ to be rendered prior to the last update. If you regenerate the bibliography, the issue should go away.

Open the post editor and click "refresh bibliography" to do that.

If that doesn't work, let me know. Also include the citation style you are using as well as your browser (including version number)

Thanks

**Comment by dsifford** [comment]
@Vitaliy-1 Let me know if the release I just pushed out fixes your issue.

**Comment by Vitaliy-1** [comment]
I just have tested plugin new release with new posts and it worked fine. Reference numbers are inline with bibliography text (tested with Chrome)

When I tried to regenerate the bibliography in the post where it was earlier - the list disappeared and subsequent work with the references on that page have leaded to WP suspending (adding new references if to be more precise). Don`t know if this problem may be systemic but I managed it simple by removing the html code of cite items in text and replacing them by new ones. In near future I plan to extensively use this plugin and will let know in case of problems.

**Comment by dsifford** [comment]
> When I tried to regenerate the bibliography in the post where it was earlier - the list disappeared and subsequent work with the references on that page have leaded to WP suspending (adding new references if to be more precise). Don`t know if this problem may be systemic but I managed it simple by removing the html code of cite items in text and replacing them by new ones. In near future I plan to extensively use this plugin and will let know in case of problems.

Can you explain this in greater detail? Can you confirm that you pressed the `Refresh Reference List` button and not the `Delete All References` button?

**Comment by Vitaliy-1** [comment]
Yes, bibliographic list on the page disappeared after pressing _Refresh Reference List_. But I already had problems with citations on that page - while bibliography list actually was on page it didn`t displayed at all in reflist editor. So after refreshing bibliographic list disappeared according to blank reflist editor.

**Comment by Vitaliy-1** [comment]
> Edge and IE - Peer Review boxes are not shown (only "null" text)
I have tested this moment once more on Edge and noted that it concerns to _American Medical Association_ citation style but not to Vancouver style or for example APA style. So there is only a little problem here.

**Comment by dsifford** [comment]
> Yes, bibliographic list on the page disappeared after pressing Refresh Reference List. But I already had problems with citations on that page - while bibliography list actually was on page it didn`t displayed at all in reflist editor. So after refreshing bibliographic list disappeared according to blank reflist editor.

I see. Let me know if this happens again and I'll dig deeper into this. For now, I'll attribute it to one of the small bugs that I fixed in the recent update.

> I have tested this moment once more on Edge and noted that it concerns to American Medical Association citation style but not to Vancouver style or for example APA style. So there is only a little problem here.

This is very interesting. There should be no interop between the Peer Review boxes and the bibliography/reference list. 

To clarify, you're saying that the peer review boxes do not render when you use AMA format, but do render when you use Vancouver or APA?

**Comment by Vitaliy-1** [comment]
> To clarify, you're saying that the peer review boxes do not render when you use AMA format, but do render when you use Vancouver or APA?
> 
Exactly :) That`s on Edge and Safari.

**Comment by dsifford** [comment]
@Vitaliy-1 if you can share a screencast of this behavior, that would be very helpful. https://www.opentest.co/

**Comment by Vitaliy-1** [comment]
> @Vitaliy-1 if you can share a screencast of this behavior, that would be very helpful. https://www.opentest.co/
>

this program is only for Chrome. On Chrome AMA format works fine.
here`s a printscreen from Edge: 
[url=http://pixs.ru/showimage/refjpg_9658379_22785169.jpg][img]http://i11.pixs.ru/thumbs/1/6/9/refjpg_9658379_22785169.jpg[/img][/url]

**Comment by dsifford** [comment]
Hm... This could possibly also be due to your locale not being processed properly.

These issues aside, can you tell me if the citations have been properly formatted for your locale? At first glance, it looks like they may still be in english/US locale.

**Comment by Vitaliy-1** [comment]
"Locale" - is for locale language?
If so I use only references in english or transliteration from cyrillic. There shouldn`t be any problem with this. And yes, citations are properly formatted.

**Comment by dsifford** [comment]
Closing this for now as this _should_ be fixed in the next update. If that's not the case, feel free to reopen. 👍
